### PR TITLE
Address compatibility issues with OTE, that are caused by the legacy code.

### PR DESCRIPTION
**Pull request by samet-akcay**
# Changes

This PR fixes the compatibility issues with OTE SDK. After tagging this version as v0.1.2+, GitHub should be fully compatible

### CODE REVIEW

**Review by ashwinvaidya17 — APPROVED** [review]
Nice! The config stuff in preprocessor addresses an issue I had in benchmarking script. Maybe we should create a ticket to add inferencer tests.

**Comment by djdameln** [comment]
Did you test this in SC yet?

**Comment by samet-akcay** [comment]
> Did you test this in SC yet?

Tests on OTE Anomalib passes, but gives a warning message. I've shared the log on teams

**Comment by samet-akcay** [comment]
> Nice! The config stuff in preprocessor addresses an issue I had in benchmarking script. Maybe we should create a ticket to add inferencer tests.

@ashwinvaidya17 , I agree, we should definitely have inference tests.

**Pull request merged**
