### PR TITLE
🔨Fix the visualization issue of inference image

### LINKED ISSUE #289: add_label in inference.py cannot put text on small image
**Describe the bug**

Function `add_label` in `inference.py` cannot put text on small image(height=18, width=43, jpeg image)

**To Reproduce**
1. Prepare small height and width of image(s), e.g. height=18, width=43, jpeg image
2. Specify `--image_path` to the image from step1
3. Run `inference.py`

**Expected behavior**
Put inferenced result on a image

**Screenshots**

image

**Hardware and Software Configuration**
- OS: Windows
- NVIDIA Driver Version [v471.11]
- CUDA Version [v11.4]
- CUDNN Version [v11.4.120]

### PR DESCRIPTION
**Pull request by ABoLei**
# Description

- Fixes #289 

- Fix the visualization issue when the input image is smaller than the canvas of inference result
- Instead of overlay the inference result(Confidence Score) on the prediction image, make the inference result as a separate line above the prediction image
- The demonstration is as below:
- input image size = 1443 * 1443
large
- input image size = 900 * 900

- input image size = 41 * 41
small

## Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://openvinotoolkit.github.io/anomalib/guides/using_pre_commit.html#pre-commit-hooks) of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

### CODE REVIEW

**Comment by ABoLei** [comment]
@samet-akcay Could you review this PR? thanks

**Comment by samet-akcay** [comment]
@ABoLei thank you for your PR. There has been some changes in the visualizer after this PR. Your PR would have some conflicts due to these changes? Can you check the development branch to see if the issue you reported still the case? If yes, we would update your PR based on the recent changes.

How does this sound?

**Comment by ABoLei** [comment]
> @ABoLei thank you for your PR. There has been some changes in the visualizer after this PR. Your PR would have some conflicts due to these changes? Can you check the development branch to see if the issue you reported still the case? If yes, we would update your PR based on the recent changes.
> 
> How does this sound?

Sure thing, I will check it later on,

**Comment by ABoLei** [comment]
@samet-akcay I fixed the conflicts and remain the changes I made, please have a look, thanks

**Comment by djdameln** [comment]
This issue is no longer present with the latest version of the visualizer.

**Pull request closed without merging**
