### PR TITLE
Make anomalib PEP 561 compliant for mypy

### LINKED ISSUE #1015: [Task]: Make anomalib PEP 561 compliant for mypy
### What is the motivation for this task?

When installing anomalib as a package, mypy starts to complain about missing type stubs. Seeing that anomalib is mostly (if not fully) typed, it would be nice to make the package PEP561 compliant (currently I ignore `anomalib` for mypy)

### Describe the solution you'd like

Make the package PEP 561 compliant. Could potentially be as easy as adding a `py.typed` at the root of the shipped package directory. Note that I am not an expert in building/shipping python packages, so I might also be wrong on this

### Additional context

https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

### PR DESCRIPTION
**Pull request by WenjingKangIntel**
# Description

- Provide a summary of the modification as well as the issue that has been resolved. List any dependencies that this modification necessitates.
This PR aims to make anomalib PEP 561 compliant for mypy:
1. Add py.typed file in package directory.
2. Include py.typed in MANIFEST.in.
reference:
https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

If we have a `test_mypy.py` for testing with the following content:
`
from anomalib.config import get_configurable_parameters, update_nncf_config
`
Before this PR, when running: `mypy test_pep561.py`, it will generate the following error.
```
test_pep561.py:1: error: Skipping analyzing "anomalib.config": module is installed, but missing library stubs or py.typed marker  [import]
test_pep561.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```
After this PR, it will have the following output:
`Success: no issues found in 1 source file
`
This shows that this PR can make anomalib PEP 561 compliant for mypy.
- Fixes #1015

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] I have added a summary of my changes to the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) (not for minor changes, docs and tests).

### CODE REVIEW

**Review by samet-akcay — APPROVED** [review]
lgtm, thanks for the contribution!

**Review by ashwinvaidya17 — COMMENTED** [review]
Do you think we need to also include a line in `setup.py`. Something like
```python
 package_data={"anomalib": ["py.typed"]},
```

**Comment by WenjingKangIntel** [comment]
> Do you think we need to also include a line in `setup.py`. Something like
> 
> ```python
>  package_data={"anomalib": ["py.typed"]},
> ```

Hi, Vaidya,
From the link:
https://setuptools.pypa.io/en/latest/userguide/datafiles.html#summary
package_data specifies additional patterns to match files that may or may not be matched by MANIFEST.in. The results turn out the content in MANIFEST.in is matched.

Some more information about:
https://packaging.python.org/en/latest/guides/using-manifest-in/
all files specified by the package_data and data_files setup() arguments and the commands in MANIFEST.in (if such a file exists) are executed in order to add and remove further files to and from the sdist.

Conclusion:
Please double check. From my understanding, adding "py.typed" to package_data is not needed.

**Comment by ashwinvaidya17** [comment]
> > Do you think we need to also include a line in `setup.py`. Something like
> > ```python
> >  package_data={"anomalib": ["py.typed"]},
> > ```
> 
> Hi, Vaidya, From the link: https://setuptools.pypa.io/en/latest/userguide/datafiles.html#summary package_data specifies additional patterns to match files that may or may not be matched by MANIFEST.in. The results turn out the content in MANIFEST.in is matched.
> 
> Some more information about: https://packaging.python.org/en/latest/guides/using-manifest-in/ all files specified by the package_data and data_files setup() arguments and the commands in MANIFEST.in (if such a file exists) are executed in order to add and remove further files to and from the sdist.
> 
> Conclusion: Please double check. From my understanding, adding "py.typed" to package_data is not needed.

I tried using both `python -m build` and `python setup.py sdist bdist_wheel` to generate distribution package. When I use `python -m build`, the `py.typed` file is present in the distribution however, if I use `python setup.py ...` then this file is missing. So, when we upload to pip, the inclusion of this file depends on what method the pip uploader uses to generate the distribution. Not sure what's the standard approach to generate distributions. @samet-akcay any thoughts on this?

**Comment by samet-akcay** [comment]
> > > Do you think we need to also include a line in `setup.py`. Something like
> > > ```python
> > >  package_data={"anomalib": ["py.typed"]},
> > > ```
> > 
> > 
> > Hi, Vaidya, From the link: https://setuptools.pypa.io/en/latest/userguide/datafiles.html#summary package_data specifies additional patterns to match files that may or may not be matched by MANIFEST.in. The results turn out the content in MANIFEST.in is matched.
> > Some more information about: https://packaging.python.org/en/latest/guides/using-manifest-in/ all files specified by the package_data and data_files setup() arguments and the commands in MANIFEST.in (if such a file exists) are executed in order to add and remove further files to and from the sdist.
> > Conclusion: Please double check. From my understanding, adding "py.typed" to package_data is not needed.
> 
> I tried using both `python -m build` and `python setup.py sdist bdist_wheel` to generate distribution package. When I use `python -m build`, the `py.typed` file is present in the distribution however, if I use `python setup.py ...` then this file is missing. So, when we upload to pip, the inclusion of this file depends on what method the pip uploader uses to generate the distribution. Not sure what's the standard approach to generate distributions. @samet-akcay any thoughts on this?

Maybe we could verify this by uploading to test-pypi?
https://packaging.python.org/en/latest/guides/using-testpypi/

**Comment by samet-akcay** [comment]
We could merge this once the CI passes.

**Comment by ORippler** [comment]
I just did an install of `anomalib==0.5.0` from pypi and `py.typed` was not present in the anomalib folder, so it's not yet fully compliant.

**Pull request merged**
