### PR TITLE
Fix efficient ad

### LINKED ISSUE #1943: 📉 Investigate the low performance of EfficientAD
# Description
Current EfficientAD implementation does not match the numbers reported in the original paper. This task is to investigate the potential root cause of this issue.

### PR DESCRIPTION
**Pull request by abc-125**
## 📝 Description

- 🛠️ Fixes #1943

Several changes to fix the performance:
- Replaced teacher weights with the ones from [Nelson1425](https://github.com/nelson1425/EfficientAD), thanks to @alexriedel1 for advice. Renamed layers to match anomalib implementation, new weights can be downloaded [here](https://drive.google.com/file/d/1AWZyFEYpIpGZhv5uArAVkIdCwbcRpr_X/view?usp=sharing).
- Removed Imagenet normalization from transforms for this model, because it is in the `forward` for every submodel already. Added checkup to detect if it is added by the user.
- The `train_batch_size` should be 1, as described in the paper. It seems hard to hardcode because it is used in the `AnomalibDataModule`, which has no access to the model's name, so I have just added a checkup to raise an error if the value is not 1.
- Removed parameter `batch_size` from `efficient_ad.yaml`, because it was affecting only Imagenet batch size, which should always be 1 according to the paper.
- Changed max epochs in `efficient_ad.yaml` to 1000, because if you don't have many images per class (as in MVTec AD), the model needs to run more epochs to finish 70000 steps, which are needed to reproduce results from the paper.

## ✨ Changes

Select what type of change your PR is:

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔨 Refactor (non-breaking change which refactors the code base)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 Documentation update
- [ ] 🔒 Security update

## ✅ Checklist

Before you submit your pull request, please make sure you have completed the following steps:

- [ ] 📋 I have summarized my changes in the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) and followed the guidelines for my type of change (skip for minor changes, documentation updates, and test enhancements).
- [ ] 📚 I have made the necessary updates to the documentation (if applicable).
- [ ] 🧪 I have written tests that support my changes and prove that my fix is effective or my feature works (if applicable).

For more information about code review checklists, see the [Code Review Checklist](https://github.com/openvinotoolkit/anomalib/blob/main/docs/source/markdown/guides/developer/code_review_checklist.md).

### CODE REVIEW

**Comment by alexriedel1** [comment]
There is one more thing when training EfficientAD:
The validation Pixel F1 Score is calculated correctly after the first training epoch. From the second epoch on, the pixel F1 stays equally low during training. The correct value can then be obtained in the test phase again. 

`engine.fit(datamodule=datamodule, model=model)`
```
Epoch 1 ... pixel_F1Score=0.2551 ...
Epoch 2 ... pixel_F1Score=0.0421 ...
Epoch 3 ... pixel_F1Score=0.0421 ...
Epoch 4 ... pixel_F1Score=0.0421 ...
```
`engine.test(datamodule=datamodule, model=model)`
```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│        image_AUROC        │            1.0            │
│       image_F1Score       │    0.9919999837875366     │
│        pixel_AUROC        │    0.9815982580184937     │
│       pixel_F1Score       │    0.7310670018196106     │
└───────────────────────────┴───────────────────────────┘
```
I think this is due to a drastic change of the anomaly map values after normalizing the anomaly maps in the first epoch. Is it possible that the pixel threshold is not resetted bevore every validation epoch?

**Comment by alexriedel1** [comment]
Do you see any performance increases? If so can you provide some numbers?

**Comment by abc-125** [comment]
> Do you see any performance increases? If so can you provide some numbers?

Sure, here are the results for image-level AUROC, seed 42, different classes of MVTec dataset, and model sizes (S or M):
- After setting `train_batch_size` to 1 and `max_epochs` to 1000 to fit the paper settings, capsules S: 87.8
- After replacing teacher weights, capsules S: 98.8, screw S: 81.2
- After removing the second Imagenet Normalization, screw S: 95.9, cable S: 94.8, transistor S: 99.8, pill M: 98.1

The last row shows results similar to the [results from the paper](https://github.com/openvinotoolkit/anomalib/files/15095591/per_scenario_results.json).

**Comment by alexriedel1** [comment]
> > Do you see any performance increases? If so can you provide some numbers?
> 
> Sure, here are the results for image-level AUROC, seed 42, different classes of MVTec dataset, and model sizes (S or M):
> 
> * After setting `train_batch_size` to 1 and `max_epochs` to 1000 to fit the paper settings, capsules S: 87.8
> * After replacing teacher weights, capsules S: 98.8, screw S: 81.2
> * After removing the second Imagenet Normalization, screw S: 95.9, cable S: 94.8, transistor S: 99.8, pill M: 98.1
> 
> The last row shows results similar to the [results from the paper](https://github.com/openvinotoolkit/anomalib/files/15095591/per_scenario_results.json).

Looks good to me!
The AUC-ROC EfficientAD paper results for comparison are:
EfficientAD S:
Screw: 0.97315
Cable: 0.92537
Transistor: 0.998

EfficientAD M:
Pill: 0.98608

Anomalib Patchcore WideResnet_50:
Screw: 0.924
Cable: 0.990
Transistor: 1.000
Pill: 0.924

**Comment by alexriedel1** [comment]
> Thanks a lot for the effort, @abc-125. The changes look good to me. If @alexriedel1 also agrees, we could merge.
> 
> @alexriedel1 can you let me know what you think? Thanks

Yes go for it!
Be sure to include the new model weights in the releases and then the weight download can be updated accordingly https://github.com/openvinotoolkit/anomalib/blob/2d59cb160aaff8d38b445d4f30a592ca289d3427/src/anomalib/models/image/efficient_ad/lightning_model.py#L35-L39

**Review by ashwinvaidya17 — APPROVED** [review]
Thanks for the fix!

**Comment by blaz-r** [comment]
Great job 😄. This also partially fixes #1813

**Comment by samet-akcay** [comment]
@ashwinvaidya17, the tests are failing. I guess it's related to the weights?

**Comment by ashwinvaidya17** [comment]
I think the tests need to be updated
image
https://github.com/openvinotoolkit/anomalib/blob/f396dd4ab6a40b7b2f95004278d328fff18c999e/tests/integration/model/test_models.py#L207

**Comment by samet-akcay** [comment]
Ah yes, of course!

**Comment by abc-125** [comment]
> I think the tests need to be updated 

Thank you, @ashwinvaidya17! I have updated the `train_batch_size` for this model in `test_models.py`.

**Comment by samet-akcay** [comment]
> > I think the tests need to be updated
> 
> Thank you, @ashwinvaidya17! I have updated the `train_batch_size` for this model in `test_models.py`.

Thanks @abc-125, merging now!

**Pull request merged**
