### PR TITLE
c_idx cast to LongTensor in random sparse projection

### PR DESCRIPTION
**Pull request by alexriedel1**
Fixing https://github.com/openvinotoolkit/anomalib/issues/111

### CODE REVIEW

**Comment by innat** [comment]
```python
components[i, c_idx.long()] = data.double()

or 

c_idx = [int(t.item()) for t in c_idx]
components[i, c_idx] = data.double()
```

It's taking really much time to get coreset from embedding. Is it expected in patchcore? I'm running on CPU with 

```python
num_workers: 1 # 36
```

**Comment by djdameln** [comment]
> It's taking really much time to get coreset from embedding. Is it expected in patchcore? I'm running on CPU with

Yes, the coreset computation in the training step is optimized for GPU. Inference should run fine on CPU.

**Review by djdameln — CHANGES_REQUESTED** [review]
Thanks for reporting and addressing this issue. I would suggest constructing `c_idx` as `long` type, like so:
```
c_idx = torch.tensor(
    sample_without_replacement(
        n_population=n_features, n_samples=nnz_idx, random_state=self.random_state
    ),
    dtype=torch.int64
)
```
That way we don't need to cast it afterwards.

**Review by djdameln — APPROVED** [review]
Thanks!

**Comment by ashwinvaidya17** [comment]
@alexriedel1 Thanks for your contribution! Let's merge after CI passes.

**Comment by ashwinvaidya17** [comment]
@alexriedel1 There seems to be a minor `black` formatting issue. https://github.com/openvinotoolkit/anomalib/runs/5315789777?check_suite_focus=true Can you address it? I think it would be convenient for you if you install pre-commit hooks. 
```bash
pip install pre-commit
pre-commit install
pre-commit run --all-files
```

**Comment by alexriedel1** [comment]
> @alexriedel1 There seems to be a minor `black` formatting issue. https://github.com/openvinotoolkit/anomalib/runs/5315789777?check_suite_focus=true Can you address it? I think it would be convenient for you if you install pre-commit hooks.
> 
> ```shell
> pip install pre-commit
> pre-commit install
> pre-commit run --all-files
> ```

I guess thats what black wanted to reformat. Unfortunately I wasnt abel to run the pre commit hooks..

**Review by ashwinvaidya17 — APPROVED** [review]
Thanks for quickly addressing this!

**Comment by ashwinvaidya17** [comment]
> I guess thats what black wanted to reformat. Unfortunately I wasnt abel to run the pre commit hooks..

Can you share the error? We will try to update the docs to address this.

**Comment by alexriedel1** [comment]
> > I guess thats what black wanted to reformat. Unfortunately I wasnt abel to run the pre commit hooks..
> 
> Can you share the error? We will try to update the docs to address this.

It's an issue on my side. I'm having strange permission issues when trying to run the hooks so dont worry..

**Pull request merged**
