### PR TITLE
Fix the imports to fit in OpenVINO 2023.3

### PR DESCRIPTION
**Pull request by prob1995**
## 📝 Description

- Fix the imports to fit in OpenVINO 2023.3 since "openvino.tools.mo" is no longer available.

## ✨ Changes

Select what type of change your PR is:

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔨 Refactor (non-breaking change which refactors the code base)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 Documentation update
- [ ] 🔒 Security update

## ✅ Checklist

Before you submit your pull request, please make sure you have completed the following steps:

- [ ] 📋 I have summarized my changes in the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) and followed the guidelines for my type of change (skip for minor changes, documentation updates, and test enhancements).
- [ ] 📚 I have made the necessary updates to the documentation (if applicable).
- [ ] 🧪 I have written tests that support my changes and prove that my fix is effective or my feature works (if applicable).

For more information about code review checklists, see the [Code Review Checklist](../docs/source/markdown/guides/developer/code_review_checklist.md).

### CODE REVIEW

**Comment by samet-akcay** [comment]
@adrianboguszewski, can you have a look at this please?

**Comment by ashwinvaidya17** [comment]
Do we need to update `requirements/openvino.txt` as well?

**Comment by prob1995** [comment]
> Do we need to update `requirements/openvino.txt` as well?

OpenVINO 2023.3.0 (the current minimum supported version) also seems to support openvino.tools.ovc without issues. Since my tests worked well, updating is likely not necessary for this case.

**Comment by samet-akcay** [comment]
@prob1995, pre-commit checks are failing due to some formatting issues. Can you do the following:

```bash
# Install the dev requirements
pip install -r requirements/dev.txt

# run the pre-commit checks
pre-commit run -a
```

**Comment by prob1995** [comment]
@samet-akcay , I accidentally deleted a line break. It's fixed now! Thanks.

image

**Review by samet-akcay — APPROVED** [review]
thanks

**Review by ashwinvaidya17 — APPROVED** [review]

**Pull request merged**
