### PR TITLE
add reorder=True argument in aupro

### PR DESCRIPTION
**Pull request by triet1102**
# Description

- Add the reorder=True in the **auc()** method in the **compute()** method of AUPRO. 

- Fixes [#943](https://github.com/openvinotoolkit/anomalib/issues/943)

## Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] I have added a summary of my changes to the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) (not for minor changes, docs and tests).

### CODE REVIEW

**Review by djdameln — APPROVED** [review]
Thanks!

**Comment by djdameln** [comment]
@samet-akcay @ashwinvaidya17 I mirrored these changes for AUROC metric in https://github.com/openvinotoolkit/anomalib/pull/945.

Please note that merging these PRs means that we no longer support PyTorch 1.8 and lower.

**Review by ashwinvaidya17 — APPROVED** [review]

**Comment by ashwinvaidya17** [comment]
@triet1102 sorry for the delay in merging this. We have now migrated from `anomalib` to `anomalib/src`. Can you update your PR to point to the file in `src`

**Comment by triet1102** [comment]
sure!

**Comment by samet-akcay** [comment]
> sure!

Thanks for your patience @triet1102! Our CI was down for some time, which is the reason why this PR had wait a bit

**Pull request merged**
