### PR TITLE
Fixed openvino_inferencer in gradio_inference

### LINKED ISSUE #971: [Bug]: gradio_inference OpenVINOInferencer error
### Describe the bug

OpenVINOInferencer in gradio_inference is instantiated with config parameter, that is no longer used, causing it to not work.

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

1. Checkout main branch
2. Enable openvino export in config.yaml
3. Train model `python tools/train.py --model padim`
4. Test inference using gradio
```bash
python tools/inference/gradio_inference.py \
       --config src/anomalib/models/padim/config.yaml \
       --weights results/padim/mvtec/bottle/run/openvino/model.bin \
       --metadata results/padim/mvtec/bottle/run/openvino/metadata.json
```

### OS information

OS information:
- OS: WIndows 10
- Python version: 3.8.10
- Anomalib version: 0.5.0.dev0
- PyTorch version: 2.0.0
- CUDA/cuDNN version: /
- GPU models and configuration: MX250
- Any other relevant information: /

### Expected behavior

Gradio is launched and can be used with OpenVINO model.

### Screenshots

image

### Pip/GitHub

GitHub

### What version/branch did you use?

main

### Configuration YAML

```yaml
dataset:
  name: mvtec
  format: mvtec
  path: ./datasets/MVTec
  category: bottle
  task: segmentation
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: padim
  backbone: resnet18
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: openvino #options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

### Logs

```shell
/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by blaz-r**
# Description

Fixed OpenVINOInferencer instantiation in gradio_inference. OpenVINOInferencer now no longer takes config parameter. This was previously fixed in openvino_inference, but not in gradio_inference, so I fixed it here as well.

- Fixes #971 

## Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] I have added a summary of my changes to the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) (not for minor changes, docs and tests).

### CODE REVIEW

**Review by ashwinvaidya17 — APPROVED** [review]
Thanks for addressing this

**Review by ashwinvaidya17 — COMMENTED** [review]
I just realized that `config` should be made optional then as it is not needed for openvino models.  We can check against the extension type and assert if `config` is not empty. Similarly, we should check whether the metadata is provided for the openvino inferencer.

**Comment by blaz-r** [comment]
> I just realized that `config` should be made optional then as it is not needed for openvino models. We can check against the extension type and assert if `config` is not empty. Similarly, we should check whether the metadata is provided for the openvino inferencer.

This is a good idea yes. It should probably be implemented in a separate PR, or do you think it can be done in this one?

**Comment by ashwinvaidya17** [comment]
> > I just realized that `config` should be made optional then as it is not needed for openvino models. We can check against the extension type and assert if `config` is not empty. Similarly, we should check whether the metadata is provided for the openvino inferencer.
> 
> This is a good idea yes. It should probably be implemented in a separate PR, or do you think it can be done in this one?

Let's do this in this one just to make it complete. We need to add just two assert statements and remove the `required=True` condition.

**Comment by blaz-r** [comment]
Good, I'll implement that and report back.

**Pull request merged**
