### PR TITLE
Refactor AUPRO metric

### PR DESCRIPTION
**Pull request by triet1102**
# Description
Hi, this is a proposal PR for the disscusion here #974 

* Before, we could not provide a mask for AUPRO calculation.
* Now, a binary `inspection_mask` can be provided during initialization to filter out points outside the mask.

Provide a summary of the modification as well as the issue that has been resolved. List any dependencies that this modification necessitates.

* Split the _compute() function into 2 sub-functions:  perform_cca() and compute_pro()
  * The perform_cca() function performs Connected Component Analysis on the target
  * The compute_pro() function computes the PRO curve, with the ability to filter unnecessary points by using the inspection_mask

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which refactors the code base)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] I have added a summary of my changes to the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) (not for minor changes, docs and tests).

### CODE REVIEW

**Review by ORippler — CHANGES_REQUESTED** [review]
This goes beyond the pure refactoring discussed [here](https://github.com/openvinotoolkit/anomalib/discussions/974). To achieve the refactor:

1. Remove `inspection_mask` (keep it in your private class that inherits from `AUPRO`)
2. Shift the flattening into `_compute`.

Doing so, you will be able to overload the `__init__` and the `_compute` functions when inheriting from `AUPRO` and anomalib does not need to support masking.

**Review by ORippler — APPROVED** [review]
LGTM now

**Review by samet-akcay — APPROVED** [review]
thanks for your contribution

**Review by djdameln — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
