### PR TITLE
Fix uncorrect download path of btech dataset

### PR DESCRIPTION
**Pull request by cjy513203427**
## 📝 Description

- The root directory in btech.yaml has a spell error.
- 🛠️ Fixes # (issue number)

## ✨ Changes

Select what type of change your PR is:

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔨 Refactor (non-breaking change which refactors the code base)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 Documentation update
- [ ] 🔒 Security update

## ✅ Checklist

Before you submit your pull request, please make sure you have completed the following steps:

- [x] 📋 I have summarized my changes in the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) and followed the guidelines for my type of change (skip for minor changes, documentation updates, and test enhancements).
- [ ] 📚 I have made the necessary updates to the documentation (if applicable).
- [x] 🧪 I have written tests that support my changes and prove that my fix is effective or my feature works (if applicable).

For more information about code review checklists, see the [Code Review Checklist](https://github.com/openvinotoolkit/anomalib/blob/main/docs/source/markdown/guides/developer/code_review_checklist.md).

### CODE REVIEW

**Review by samet-akcay — APPROVED** [review]
@cjy513203427, thanks for the fix. Our CI is out of order at the moment. We will merge this PR as soon as fixing our CI.

**Comment by cjy513203427** [comment]
> @cjy513203427, thanks for the fix. Our CI is out of order at the moment. We will merge this PR as soon as fixing our CI.

Thanks for the great work again!

**Comment by cjy513203427** [comment]
```
bash 
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...............................................................Passed
check for added large files..............................................Passed
debug statements (python)................................................Passed
detect private key.......................................................Passed
ruff.....................................................................Passed
ruff-format..............................................................Passed
mypy.....................................................................Passed
bandit...................................................................Passed
nbqa-ruff................................................................Failed
- hook id: nbqa-ruff
- exit code: 1

error: `ruff <path>` has been removed. Use `ruff check <path>` instead.

prettier.................................................................Failed
- hook id: prettier
- files were modified by this hook

CHANGELOG.md

markdownlint.............................................................Passed
pre-commit: exit 1 ([60](https://github.com/openvinotoolkit/anomalib/actions/runs/9792299662/job/27175927191?pr=2171#step:5:61).26 seconds) /home/runner/work/anomalib/anomalib> pre-commit run --all-files pid=1953
  pre-commit: FAIL code 1 (70.67=setup[10.41]+cmd[60.26] seconds)
  evaluation failed :( (71.19 seconds)
Error: Process completed with exit code 1.
```

Hi. Could you tell me how I can solve the failed Pre-Merge Checks / Code-Quality-Checks (pull_request)?

**Comment by samet-akcay** [comment]
@cjy513203427, I'm merging this to a fix branch, from which I'll sort out the rest.

**Pull request merged**
