### PR TITLE
[BUGFIX] Use `Path.is_dir` instead of `Path.suffix == ""`

### PR DESCRIPTION
**Pull request by strelka145**
# Description

The original code only determines what the path points to based on the presence or absence of the extension. With this, if you specify a directory name that includes "." in the output option, it will be mistaken for a file name. As a result, when visualizer.save was executed in anomalib/tools/inference/torch_inference.py, an error would occur or the file name would not be output as expected.
This fix corrects this bug by using .is_dir() to determine what the path points to.

## Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] I have added a summary of my changes to the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) (not for minor changes, docs and tests).

### CODE REVIEW

**Comment by samet-akcay** [comment]
@strelka145, thanks for the PR. Your proposal makes sense; however, there are number of tests that fail after this change. We need to sort these out to be able to merge your PR.

**Comment by strelka145** [comment]
This PR(https://github.com/openvinotoolkit/anomalib/pull/924)  fails in exactly the same way even though he only changed the README. Is this test working correctly?

**Comment by samet-akcay** [comment]
Ah, it is the `kornia` package. Their recent version broke `anomalib`. We need to use the previous version for now.. See the details here. https://github.com/openvinotoolkit/anomalib/issues/920

**Review by djdameln — APPROVED** [review]

**Review by samet-akcay — APPROVED** [review]
Thanks for your contribution and patience for this PR to be merged!

**Pull request merged**
