### PR TITLE
Fix issue in tutorial

### LINKED ISSUE #984: [Task]: Drift between code and quick-start-toturial
### What is the motivation for this task?

When I follow this Training with Custom Data -guide: https://openvinotoolkit.github.io/anomalib/how_to_guides/train_custom_data.html I cannot run the training: python tools/train.py --config custom_padim.yaml. Where the config is as in the tutorial. I get the this error: AttributeError: 'NoneType' object has no attribute 'keys'. When I guess is most likely becuase there is no data, but the I checked the paths and the dataset hazelnut_toy. 

### Describe the solution you'd like

Updated guide..

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ravindu987**
# Description

- There were several troublesome issues in the train-custom-data [tutorial](https://openvinotoolkit.github.io/anomalib/how_to_guides/train_custom_data.html) 
- Updated the relevant .rst [file](https://github.com/Ravindu987/anomalib/blob/Fix-Tutorial/docs/source/how_to_guides/train_custom_data.rst) 

- Fixes #984 

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] I have added a summary of my changes to the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) (not for minor changes, docs and tests).

### CODE REVIEW

**Review by ashwinvaidya17 — APPROVED** [review]
Thanks for fixing this!

**Comment by ashwinvaidya17** [comment]
Can you run pre-commit locally? The CI fails on linting checks.

**Comment by Ravindu987** [comment]
> Can you run pre-commit locally? The CI fails on linting checks.

Sorry for the inconvenience caused. Ran the pre-commit now and passed the tests.

**Review by djdameln — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
