### PR TITLE
Fix benchmark

### LINKED ISSUE #1149: [Bug]: benchmarking type error
### Describe the bug

Hi,

Following the docs of benchmarking, the simple command of "`python tools/benchmarking/benchmark.py --config tools/benchmarking/benchmark_params.yaml`" produces unexpected results.

An exception of TypeError was thrown out indicating that the path value was invalid.

When checking the code in benchmark.py, line 114, I found this:

passing `model_config` which is a dict, to `get_torch_throughput` which expects a path.

I reckon this is a bug if I am not wrong in somewhere.

Thank you if you can help to verify and fix this.

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

1. Install
2. Prepare datasets
3. Run command "python tools/benchmarking/benchmark.py --config tools/benchmarking/benchmark_params.yaml"

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.8.10]
- Anomalib version: [e.g. 0.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3050]

### Expected behavior

Should run benchmarks normally and no TypeErrors

### Screenshots

_No response_

### Pip/GitHub

pip

### What version/branch did you use?

_No response_

### Configuration YAML

```yaml
seed: 42
compute_openvino: false
hardware:
  # - cpu
  - gpu
writer:
  - wandb
  - tensorboard
dataset:
    category:
      - bottle
      - cable
      - capsule
      - carpet
      - grid
      - hazelnut
      - leather
      - metal_nut
      - pill
      - screw
      - tile
      - toothbrush
      - transistor
      - wood
      - zipper
    image_size: [224]
  model_name:
    - padim
    - patchcore
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/young/ppp/py_learn/IndustrailAnomalyDetection/anomalib/tools/benchmarking/benchmark.py", line 69, in wrapper
    value = func(*args, **kwargs)
  File "/home/young/ppp/py_learn/IndustrailAnomalyDetection/anomalib/tools/benchmarking/benchmark.py", line 114, in get_single_model_metrics
    throughput = get_torch_throughput(model_config, model, datamodule.test_dataloader().dataset)
  File "/home/young/ppp/py_learn/IndustrailAnomalyDetection/anomalib/src/anomalib/utils/sweep/helpers/inference.py", line 29, in get_torch_throughput
    model_path = Path(model_path)
  File "/usr/lib/python3.8/pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not DictConfig
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by blaz-r**
# Description

There was a problem where TorchInferencer was changed to no longer take config and model, but rather path to model. This also reflected in functions used to benchmark torch models. Required change was therefore update of calling parameters for `get_torch_throughput` and also adding instruction to export torch model to be used.

- Fixes #1149 

## Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] I have added a summary of my changes to the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) (not for minor changes, docs and tests).

### CODE REVIEW

**Comment by blaz-r** [comment]
I now also added test that cover code to obtain throughput from sweep.

**Comment by blaz-r** [comment]
Codacy generates one warning. This happens since in my tests `generate_results_dir` is a fixture and imported from other module. Because it is a fixture it's not directly used, therefore producing a warning.
I'm not sure what's the best practice here. Maybe I shouldn't use fixtures from other modules, but that would introduce code duplicating.

**Comment by blaz-r** [comment]
The thing is that `generate_results_dir` is inside of `tests.pre_merge.deploy.test_inferencer` but the tests I wrote are inside `tests/pre_merge/utils/sweep/test_throughput.py`. I have a feeling that using fixture from other module is not a good idea, but it does exactly what is needed for this test. So what would be the best thing to do here? One option would be to create conftest in pre_merge directory, but then again I'm not sure if that is a good idea, so I'd appreciate all the advice.

**Comment by blaz-r** [comment]
I now added conftest which contains path to file where needed fixture is defined. I think this should be good now.

**Review by ashwinvaidya17 — APPROVED** [review]
I am fine with these changes. Our entire test suit is going to undergo a refactor so the conftest workaround is temporary anyways. Thanks again

**Comment by blaz-r** [comment]
Well, as it turns out conftest can't have pytest_plugin in this configuration. The other option I've seen is that you just import them in conftest so I'll tryy that and we'll see.

**Comment by blaz-r** [comment]
> I am fine with these changes. Our entire test suit is going to undergo a refactor so the conftest workaround is temporary anyways. Thanks again

I just put slightly modified code into conftest. This way it should work and pytest shouldn't have problems as well.

**Comment by blaz-r** [comment]
@samet-akcay all check are now passing.

**Pull request merged**
