### PR TITLE
Improved speed and memory usage of mean+std calculation

### LINKED ISSUE #1454: [Task]: Prevent EfficientAD Looping Twice Over Teacher Outputs (Solutions included)
### What is the motivation for this task?

This is a continuation of the discussion at #1301. 

Recap: The "per-channel" mean and standard deviation of the teacher model needs to be calculated at the beginning of training. The initial solution was essentially to pass all batches from the dataset through the teacher model and collect the outputs. While collecting the outputs the "per-channel" mean is calculated. Then, the outputs are looped through a second time to calculate the "per-channel" standard deviation. This method is very memory-intensive since all outputs must be in memory at once. To reduce the memory consumption, the function was changed to no longer store the outputs but instead regenerate them for the standard deviation calculations lowering the memory usage at the cost of computation time. 

 It was suggested in the issue that an iterative solution should be implemented. This would prevent the recalculation of the outputs while also keeping the memory usage low. However, there were concerns over the stability and accuracy of an iterative solution.

### Describe the solution you'd like

I implemented 2 possible iterative algorithms and compared the results to the original non-iterative versions.

I first implemented the algorithm described [here](https://math.stackexchange.com/a/2148949), I will call it algorithm A. In the issue, another algorithm was linked ([link](https://math.stackexchange.com/a/1769248)) which I also implemented, I will call it algorithm B. 

There was discussion about whether these incremental methods would be stable and accurate. To test accuracy, I ran some tests where I would have the two new algorithms run alongside the existing algorithm in a standard training run. The default Efficient AD config was used for each run. This way I could directly compare the output of each algorithm. For the data, I just used the imagenet validation data that is automatically used at the beginning of training. 

To compare accuracy, I use mean squared error between the different outputs. To determine memory added, I cleared the cache before each function, then tracked the change in allocated memory (using `torch.cuda.memory_allocated(0)` ) from the start to the end of the function (before the return). Speed was calculated simply using `time.perf_counter()`. 

Below are the compiled statistics averaged over several runs (algorithm call order was randomized):

| Algorithm |  Mean MSE  |  STD MSE   | Added Memory | Speed Relative to Base Algorithm (Avg. 25 Runs) |
| :-------: | :--------: | :--------: | :----------: | :---------------------------------------------: |
|   Base    |     -      |     -      |  12.403 MB   |                       1x                        |
|     A     | 3.7644e-13 | 6.1821e-14 |  4.8292 MB   |                     1.993x                      |
|     B     | 3.6637e-13 | 6.5522e-14 |  14.460 MB   |                     1.974x                      |

These tests were performed using an RTX 3080 on Ubuntu 22.04 with an unaltered anomalib development python environment. Using driver version: 535.113.01.

Since both new algorithms loop through the data only once rather than than twice like the current algorithm does, they are approximately two times faster since the majority of the time in each algorithm is spent loading data.

These tests are enough to convince me that these incremental algorithms are sufficiently accurate but I understand if some want more rigorous testing. Since algorithm A was similar in accuracy to B and uses less memory than the other two, that is the algorithm I have committed for a pull request. I am open to suggestions or improvements to either of these algorithms. 

Once I submit the PR I will link it below.

##### Reference (Current)

```python
@torch.no_grad()
def teacher_channel_mean_std(self, dataloader: DataLoader) -> dict[str, Tensor]:
    """Calculate the mean and std of the teacher models activations.

    Args:
        dataloader (DataLoader): Dataloader of the respective dataset.

    Returns:
        dict[str, Tensor]: Dictionary of channel-wise mean and std
    """
    y_means = []
    means_distance = []

    logger.info("Calculate teacher channel mean and std")
    for batch in tqdm.tqdm(dataloader, desc="Calculate teacher channel mean", position=0, leave=True):
        y = self.model.teacher(batch["image"].to(self.device))
        y_means.append(torch.mean(y, dim=[0, 2, 3]))

    channel_mean = torch.mean(torch.stack(y_means), dim=0)[None, :, None, None]

    for batch in tqdm.tqdm(dataloader, desc="Calculate teacher channel std", position=0, leave=True):
        y = self.model.teacher(batch["image"].to(self.device))
        distance = (y - channel_mean) ** 2
        means_distance.append(torch.mean(distance, dim=[0, 2, 3]))

    channel_var = torch.mean(torch.stack(means_distance), dim=0)[None, :, None, None]
    channel_std = torch.sqrt(channel_var)
    return {"mean": channel_mean, "std": channel_std}
```

##### Algorithm A

```python
@torch.no_grad()
def teacher_channel_mean_std(self, dataloader: DataLoader) -> dict[str, Tensor]:
    """Calculate the mean and std of the teacher models activations.
    Adapted from https://math.stackexchange.com/a/2148949

    Args:
        dataloader (DataLoader): Dataloader of the respective dataset.

    Returns:
        dict[str, Tensor]: Dictionary of channel-wise mean and std
    """

    arrays_defined = False
    n: torch.Tensor | None = None
    chanel_sum: torch.Tensor | None = None
    chanel_sum_sqr: torch.Tensor | None = None

    for batch in tqdm.tqdm(dataloader, desc="Calculate teacher channel mean & std", position=0, leave=True):
        y = self.model.teacher(batch["image"].to(self.device))
        if not arrays_defined:
            _, num_channels, _, _ = y.shape
            n = torch.zeros((num_channels,), dtype=torch.int64, device=y.device)
            chanel_sum = torch.zeros((num_channels,), dtype=torch.float64, device=y.device)
            chanel_sum_sqr = torch.zeros((num_channels,), dtype=torch.float64, device=y.device)
            arrays_defined = True

        n += y[:, 0].numel()
        chanel_sum += torch.sum(y, dim=[0, 2, 3])
        chanel_sum_sqr += torch.sum(y ** 2, dim=[0, 2, 3])

    assert n is not None

    channel_mean = chanel_sum / n

    channel_std = (torch.sqrt((chanel_sum_sqr / n) - (channel_mean ** 2))).float()[None, :, None, None]
    channel_mean = channel_mean.float()[None, :, None, None]

    return {"mean": channel_mean, "std": channel_std}
```

##### Algorithm B

```python
@torch.no_grad()
def teacher_channel_mean_std_B(self, dataloader: DataLoader) -> dict[str, Tensor]:
    """Calculate the mean and std of the teacher models activations.
    Adapted from https://math.stackexchange.com/a/1769248

    Args:
        dataloader (DataLoader): Dataloader of the respective dataset.

    Returns:
        dict[str, Tensor]: Dictionary of channel-wise mean and std
    """

    arrays_defined = False
    n: torch.Tensor | None = None
    channel_mean: torch.Tensor | None = None
    M2: torch.Tensor | None = None

    for batch in tqdm.tqdm(dataloader, desc="Calculate teacher channel mean & std", position=0, leave=True):
        y = self.model.teacher(batch["image"].to(self.device))
        if not arrays_defined:
            _, num_channels, _, _ = y.shape
            n = torch.zeros((1, num_channels, 1, 1), dtype=torch.int64, device=y.device)
            channel_mean = torch.zeros((1, num_channels, 1, 1), dtype=torch.float64, device=y.device)
            M2 = torch.zeros((1, num_channels, 1, 1), dtype=torch.float64, device=y.device)
            arrays_defined = True

        n += y[:, 0].numel()
        delta = y - channel_mean
        channel_mean += torch.sum(delta / n, dim=[0, 2, 3], keepdim=True)
        M2 += torch.sum(delta * (y - channel_mean), dim=[0, 2, 3], keepdim=True)

    assert n is not None

    channel_mean = channel_mean.float()
    channel_std = torch.sqrt(M2 / n).float()

    return {"mean": channel_mean, "std": channel_std}
```

### Additional context

I have a version of `lightning_model.py` with the new function that passes all pre-commit checks [here](https://github.com/belfner/anomalib/commit/056e26fa829a95e7279e68ef303ad7447ca4e40f). If you deem my solution adequate I am happy to submit a pull request (though I am unable to run the tests). Or if changes need to be made I am also happy to work with you to get those implemented. Let me know if you have any questions.

I have also appended my `lightning_model.py` that I used to gather these statistics.

<details close>
  <summary>lightning_model.py</summary>

```python
"""EfficientAd: Accurate Visual Anomaly Detection at Millisecond-Level Latencies.
https://arxiv.org/pdf/2303.14535.pdf
"""

# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import logging
import secrets
import time
from functools import wraps
from pathlib import Path

import albumentations as A
import numpy as np
import torch
import tqdm
from albumentations.pytorch import ToTensorV2
from lightning_fabric import seed_everything
from omegaconf import DictConfig, ListConfig
from pytorch_lightning.utilities.types import STEP_OUTPUT
from torch import Tensor, optim
from torch.utils.data import DataLoader
from torchmetrics.functional import mean_squared_error
from torchvision.datasets import ImageFolder

from anomalib.data.utils import DownloadInfo, download_and_extract
from anomalib.models.components import AnomalyModule
from .torch_model import EfficientAdModel, EfficientAdModelSize, reduce_tensor_elems
torch.use_deterministic_algorithms(True)
logger = logging.getLogger(__name__)

IMAGENETTE_DOWNLOAD_INFO = DownloadInfo(
    name="imagenette2.tgz",
    url="https://s3.amazonaws.com/fast-ai-imageclas/imagenette2.tgz",
    hash="fe2fc210e6bb7c5664d602c3cd71e612",
)

WEIGHTS_DOWNLOAD_INFO = DownloadInfo(
    name="efficientad_pretrained_weights.zip",
    url="https://github.com/openvinotoolkit/anomalib/releases/download/efficientad_pretrained_weights/efficientad_pretrained_weights.zip",
    hash="ec6113d728969cd233271eeed7d692f2",
)

LOG_MEM = True

def profile(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        s = time.perf_counter()
        ret = func(*args, **kwargs)
        e = time.perf_counter()
        duration = e - s
        print(f'{func.__name__} took {duration} s')
        return ret, duration

    return wrapper


class TransformsWrapper:
    def __init__(self, t: A.Compose):
        self.transforms = t

    def __call__(self, img, *args, **kwargs):
        return self.transforms(image=np.array(img))


class EfficientAd(AnomalyModule):
    """PL Lightning Module for the EfficientAd algorithm.

    Args:
        teacher_file_name (str): path to the pre-trained teacher model
        teacher_out_channels (int): number of convolution output channels
        image_size (tuple): size of input images
        model_size (str): size of student and teacher model
        lr (float): learning rate
        weight_decay (float): optimizer weight decay
        padding (bool): use padding in convoluional layers
        pad_maps (bool): relevant if padding is set to False. In this case, pad_maps = True pads the
            output anomaly maps so that their size matches the size in the padding = True case.
        batch_size (int): batch size for imagenet dataloader
    """

    def __init__(
            self,
            teacher_out_channels: int,
            image_size: tuple[int, int],
            model_size: EfficientAdModelSize = EfficientAdModelSize.S,
            lr: float = 0.0001,
            weight_decay: float = 0.00001,
            padding: bool = False,
            pad_maps: bool = True,
            batch_size: int = 1,
    ) -> None:
        super().__init__()

        self.model_size = model_size
        self.model: EfficientAdModel = EfficientAdModel(
            teacher_out_channels=teacher_out_channels,
            input_size=image_size,
            model_size=model_size,
            padding=padding,
            pad_maps=pad_maps,
        )
        self.batch_size = batch_size
        self.image_size = image_size
        self.lr = lr
        self.weight_decay = weight_decay

        self.prepare_pretrained_model()
        self.prepare_imagenette_data()

    def prepare_pretrained_model(self) -> None:
        pretrained_models_dir = Path("./pre_trained/")
        if not pretrained_models_dir.is_dir():
            download_and_extract(pretrained_models_dir, WEIGHTS_DOWNLOAD_INFO)
        teacher_path = (
                pretrained_models_dir / "efficientad_pretrained_weights" / f"pretrained_teacher_{self.model_size}.pth"
        )
        logger.info(f"Load pretrained teacher model from {teacher_path}")
        self.model.teacher.load_state_dict(torch.load(teacher_path, map_location=torch.device(self.device)))

    def prepare_imagenette_data(self) -> None:
        self.data_transforms_imagenet = A.Compose(
            [  # We obtain an image P ∈ R 3×256×256 from ImageNet by choosing a random image,
                A.Resize(self.image_size[0] * 2, self.image_size[1] * 2),  # resizing it to 512 × 512,
                A.ToGray(p=0.3),  # converting it to gray scale with a probability of 0.3
                A.CenterCrop(self.image_size[0], self.image_size[1]),  # and cropping the center 256 × 256 pixels
                A.ToFloat(always_apply=False, p=1.0, max_value=255),
                ToTensorV2(),
            ]
        )

        imagenet_dir = Path("./datasets/imagenette")
        if not imagenet_dir.is_dir():
            download_and_extract(imagenet_dir, IMAGENETTE_DOWNLOAD_INFO)
        imagenet_dataset = ImageFolder(imagenet_dir, transform=TransformsWrapper(t=self.data_transforms_imagenet))
        self.imagenet_loader = DataLoader(imagenet_dataset, batch_size=self.batch_size, shuffle=True, pin_memory=True)
        self.imagenet_iterator = iter(self.imagenet_loader)

    @profile
    @torch.no_grad()
    def teacher_channel_mean_std(self, dataloader: DataLoader) -> dict[str, Tensor]:
        if LOG_MEM:
            torch.cuda.empty_cache()
            a = torch.cuda.memory_allocated(0)
        """Calculate the mean and std of the teacher models activations.

        Args:
            dataloader (DataLoader): Dataloader of the respective dataset.

        Returns:
            dict[str, Tensor]: Dictionary of channel-wise mean and std
        """
        y_means = []
        means_distance = []

        logger.info("Calculate teacher channel mean and std")
        for batch in tqdm.tqdm(dataloader, desc="Calculate teacher channel mean", position=0, leave=True):
            y = self.model.teacher(batch["image"].to(self.device))
            y_means.append(torch.mean(y, dim=[0, 2, 3]))

        channel_mean = torch.mean(torch.stack(y_means), dim=0)[None, :, None, None]

        for batch in tqdm.tqdm(dataloader, desc="Calculate teacher channel std", position=0, leave=True):
            y = self.model.teacher(batch["image"].to(self.device))
            distance = (y - channel_mean) ** 2
            means_distance.append(torch.mean(distance, dim=[0, 2, 3]))

        channel_var = torch.mean(torch.stack(means_distance), dim=0)[None, :, None, None]
        channel_std = torch.sqrt(channel_var)
        if LOG_MEM:
            print(f'Allocated: {torch.cuda.memory_allocated(0) - a} bytes')
        return {"mean": channel_mean, "std": channel_std}

    @profile
    @torch.no_grad()
    def teacher_channel_mean_std_A(self, dataloader: DataLoader) -> dict[str, Tensor]:
        if LOG_MEM:
            torch.cuda.empty_cache()
            a = torch.cuda.memory_allocated(0)
        """Calculate the mean and std of the teacher models activations.
        Adapted from https://math.stackexchange.com/a/2148949

        Args:
            dataloader (DataLoader): Dataloader of the respective dataset.

        Returns:
            dict[str, Tensor]: Dictionary of channel-wise mean and std
        """

        arrays_defined = False
        n: torch.Tensor | None = None
        chanel_sum: torch.Tensor | None = None
        chanel_sum_sqr: torch.Tensor | None = None

        for batch in tqdm.tqdm(dataloader, desc="Calculate teacher channel mean & std", position=0, leave=True):
            y = self.model.teacher(batch["image"].to(self.device))
            if not arrays_defined:
                _, num_channels, _, _ = y.shape
                n = torch.zeros((num_channels,), dtype=torch.int64, device=y.device)
                chanel_sum = torch.zeros((num_channels,), dtype=torch.float64, device=y.device)
                chanel_sum_sqr = torch.zeros((num_channels,), dtype=torch.float64, device=y.device)
                arrays_defined = True

            n += y[:, 0].numel()
            chanel_sum += torch.sum(y, dim=[0, 2, 3])
            chanel_sum_sqr += torch.sum(y ** 2, dim=[0, 2, 3])

		assert n is not None

        channel_mean = chanel_sum / n

        channel_std = (torch.sqrt((chanel_sum_sqr / n) - (channel_mean ** 2))).float()[None, :, None, None]
        channel_mean = channel_mean.float()[None, :, None, None]
        if LOG_MEM:
            print(f'Allocated: {torch.cuda.memory_allocated(0) - a} bytes')
        return {"mean": channel_mean, "std": channel_std}

    @profile
    @torch.no_grad()
    def teacher_channel_mean_std_B(self, dataloader: DataLoader) -> dict[str, Tensor]:
        if LOG_MEM:
            torch.cuda.empty_cache()
            a = torch.cuda.memory_allocated(0)
        """Calculate the mean and std of the teacher models activations.
        Adapted from https://math.stackexchange.com/a/1769248

        Args:
            dataloader (DataLoader): Dataloader of the respective dataset.

        Returns:
            dict[str, Tensor]: Dictionary of channel-wise mean and std
        """

        arrays_defined = False
        n: torch.Tensor | None = None
        channel_mean: torch.Tensor | None = None
        M2: torch.Tensor | None = None

        for batch in tqdm.tqdm(dataloader, desc="Calculate teacher channel mean & std", position=0, leave=True):
            y = self.model.teacher(batch["image"].to(self.device))
            if not arrays_defined:
                _, num_channels, _, _ = y.shape
                n = torch.zeros((1, num_channels, 1, 1), dtype=torch.int64, device=y.device)
                channel_mean = torch.zeros((1, num_channels, 1, 1), dtype=torch.float64, device=y.device)
                M2 = torch.zeros((1, num_channels, 1, 1), dtype=torch.float64, device=y.device)
                arrays_defined = True

            n += y[:, 0].numel()
            delta = y - channel_mean
            channel_mean += torch.sum(delta / n, dim=[0, 2, 3], keepdim=True)
            M2 += torch.sum(delta * (y - channel_mean), dim=[0, 2, 3], keepdim=True)

        assert n is not None

        channel_mean = channel_mean.float()
        channel_std = torch.sqrt(M2 / n).float()
        if LOG_MEM:
            print(f'Allocated: {torch.cuda.memory_allocated(0) - a} bytes')
        return {"mean": channel_mean, "std": channel_std}

    @torch.no_grad()
    def map_norm_quantiles(self, dataloader: DataLoader) -> dict[str, Tensor]:
        """Calculate 90% and 99.5% quantiles of the student(st) and autoencoder(ae).

        Args:
            dataloader (DataLoader): Dataloader of the respective dataset.

        Returns:
            dict[str, Tensor]: Dictionary of both the 90% and 99.5% quantiles
            of both the student and autoencoder feature maps.
        """
        maps_st = []
        maps_ae = []
        logger.info("Calculate Validation Dataset Quantiles")
        for batch in tqdm.tqdm(dataloader, desc="Calculate Validation Dataset Quantiles", position=0, leave=True):
            for img, label in zip(batch["image"], batch["label"]):
                if label == 0:  # only use good images of validation set!
                    output = self.model(img.to(self.device))
                    map_st = output["map_st"]
                    map_ae = output["map_ae"]
                    maps_st.append(map_st)
                    maps_ae.append(map_ae)

        qa_st, qb_st = self._get_quantiles_of_maps(maps_st)
        qa_ae, qb_ae = self._get_quantiles_of_maps(maps_ae)
        return {"qa_st": qa_st, "qa_ae": qa_ae, "qb_st": qb_st, "qb_ae": qb_ae}

    def _get_quantiles_of_maps(self, maps: list[Tensor]) -> tuple[Tensor, Tensor]:
        """Calculate 90% and 99.5% quantiles of the given anomaly maps.

        If the total number of elements in the given maps is larger than 16777216
        the returned quantiles are computed on a random subset of the given
        elements.

        Args:
            maps (list[Tensor]): List of anomaly maps.

        Returns:
            tuple[Tensor, Tensor]: Two scalars - the 90% and the 99.5% quantile.
        """

        maps_flat = reduce_tensor_elems(torch.cat(maps))
        qa = torch.quantile(maps_flat, q=0.9).to(self.device)
        qb = torch.quantile(maps_flat, q=0.995).to(self.device)
        return qa, qb

    def configure_optimizers(self) -> optim.Optimizer:
        optimizer = optim.Adam(
            list(self.model.student.parameters()) + list(self.model.ae.parameters()),
            lr=self.lr,
            weight_decay=self.weight_decay,
        )
        num_steps = min(
            self.trainer.max_steps, self.trainer.max_epochs * len(self.trainer.datamodule.train_dataloader())
        )
        scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=int(0.95 * num_steps), gamma=0.1)
        return {"optimizer": optimizer, "lr_scheduler": scheduler}

    def compare_output(self):
        seed_everything(1001)
        baseline_0, _ = self.teacher_channel_mean_std(self.trainer.datamodule.train_dataloader())
        seed_everything(1001)
        baseline_1, _ = self.teacher_channel_mean_std(self.trainer.datamodule.train_dataloader())
        print('Baseline comparison')
        print(mean_squared_error(baseline_0['mean'], baseline_1['mean']))
        print(mean_squared_error(baseline_0['std'], baseline_1['std']))
        seed_everything(1001)
        A_output, _ = self.teacher_channel_mean_std_A(self.trainer.datamodule.train_dataloader())
        seed_everything(1001)
        B_output, _ = self.teacher_channel_mean_std_B(self.trainer.datamodule.train_dataloader())
        seed_everything(1001)
        channel_mean_std, _ = self.teacher_channel_mean_std(self.trainer.datamodule.train_dataloader())
        print('Full comparison')
        print('A')
        print(mean_squared_error(channel_mean_std['mean'], A_output['mean']))
        print(mean_squared_error(channel_mean_std['std'], A_output['std']))
        print('B')
        print(mean_squared_error(channel_mean_std['mean'], B_output['mean']))
        print(mean_squared_error(channel_mean_std['std'], B_output['std']))


    def compare_speed(self):
        funcs = [self.teacher_channel_mean_std, self.teacher_channel_mean_std_A, self.teacher_channel_mean_std_B]

        for func in funcs:
            func(self.trainer.datamodule.train_dataloader())

        import random
        results = {func.__name__: 0 for func in funcs}
        for x in range(25):
            seed = secrets.randbits(30)
            random.seed(seed)
            random.shuffle(funcs)
            for func in funcs:
                seed_everything(seed)
                results[func.__name__] += func(self.trainer.datamodule.train_dataloader())[1]
        print(results)

    def on_train_start(self) -> None:
        global LOG_MEM
        """Calculate or load the channel-wise mean and std of the training dataset and push to the model."""
        if not self.model.is_set(self.model.mean_std):
            # channel_mean_std = self.teacher_channel_mean_std(self.trainer.datamodule.train_dataloader())
            # self.model.mean_std.update(channel_mean_std)
            self.compare_output()
            LOG_MEM = False
            self.compare_speed()
            exit()

    def training_step(self, batch: dict[str, str | Tensor], *args, **kwargs) -> dict[str, Tensor]:
        """Training step for EfficientAd returns the student, autoencoder and combined loss.

        Args:
            batch (batch: dict[str, str | Tensor]): Batch containing image filename, image, label and mask

        Returns:
          Loss.
        """
        del args, kwargs  # These variables are not used.

        try:
            # infinite dataloader; [0] getting the image not the label
            batch_imagenet = next(self.imagenet_iterator)[0]["image"].to(self.device)
        except StopIteration:
            self.imagenet_iterator = iter(self.imagenet_loader)
            batch_imagenet = next(self.imagenet_iterator)[0]["image"].to(self.device)

        loss_st, loss_ae, loss_stae = self.model(batch=batch["image"], batch_imagenet=batch_imagenet)

        loss = loss_st + loss_ae + loss_stae
        self.log("train_st", loss_st.item(), on_epoch=True, prog_bar=True, logger=True)
        self.log("train_ae", loss_ae.item(), on_epoch=True, prog_bar=True, logger=True)
        self.log("train_stae", loss_stae.item(), on_epoch=True, prog_bar=True, logger=True)
        self.log("train_loss", loss.item(), on_epoch=True, prog_bar=True, logger=True)
        return {"loss": loss}

    def on_validation_start(self) -> None:
        """
        Calculate the feature map quantiles of the validation dataset and push to the model.
        """
        if (self.current_epoch + 1) == self.trainer.max_epochs:
            map_norm_quantiles = self.map_norm_quantiles(self.trainer.datamodule.val_dataloader())
            self.model.quantiles.update(map_norm_quantiles)

    def validation_step(self, batch: dict[str, str | Tensor], *args, **kwargs) -> STEP_OUTPUT:
        """Validation Step of EfficientAd returns anomaly maps for the input image batch

        Args:
          batch (dict[str, str | Tensor]): Input batch

        Returns:
          Dictionary containing anomaly maps.
        """
        del args, kwargs  # These variables are not used.

        batch["anomaly_maps"] = self.model(batch["image"])["anomaly_map"]

        return batch


class EfficientAdLightning(EfficientAd):
    """PL Lightning Module for the EfficientAd Algorithm.

    Args:
        hparams (DictConfig | ListConfig): Model params
    """

    def __init__(self, hparams: DictConfig | ListConfig) -> None:
        super().__init__(
            teacher_out_channels=hparams.model.teacher_out_channels,
            model_size=hparams.model.model_size,
            lr=hparams.model.lr,
            weight_decay=hparams.model.weight_decay,
            padding=hparams.model.padding,
            pad_maps=hparams.model.pad_maps,
            image_size=hparams.dataset.image_size,
            batch_size=hparams.dataset.train_batch_size,
        )
        self.hparams: DictConfig | ListConfig  # type: ignore
        self.save_hyperparameters(hparams)

```
</details>

### PR DESCRIPTION
**Pull request by belfner**
## Description

Implemented an iterative algorithm to calculate the per channel mean and std of the teacher model preventing the need for computing the model outputs twice. 

- Fixes #1454
- **TODO:** The algorithm may need further testing
- **TODO:** There may be a way to initialize the algorithm outside of the loop 

## Changes

<details>
<summary>Describe the changes you made</summary>

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

</details>

## Checklist

<details>
<summary>Ensure that you followed the following</summary>

- [ ] I have added a summary of my changes to the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) (not for minor changes, docs and tests).
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas (If applicable)
- [ ] I have made corresponding changes to the documentation (If applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (If applicable)

</details>

### CODE REVIEW

**Comment by samet-akcay** [comment]
@alexriedel1, will you be able to review this PR please?

**Comment by alexriedel1** [comment]
@belfner awesome! Thats the correct way to calculate mean and std here :)
I did some tests and the results are all correct, thanks

**Review by samet-akcay — APPROVED** [review]
Thanks for your contribution @belfner !

**Comment by belfner** [comment]
Glad it worked out

**Pull request merged**
