### PR TITLE
ADD pipeline training and inference UI

### PR DESCRIPTION
**Pull request by vnk8071**
# Description

As issue #721, I have already create a pipeline for training and inferencing using UI. More details in README.md in tools/pipeline folder

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which refactors the code base)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

### CODE REVIEW

**Comment by vnk8071** [comment]
I forgot to add label enhancement and I would assign @ashwinvaidya17 to review my PR.

**Comment by ashwinvaidya17** [comment]
Thanks for your hard work! The team is a bit occupied with some stuff but we will review your PR soon :)

**Comment by jpcbertoldo** [comment]
The idea of having a web app for interacting with anomalib is really cool, but IMO it would be better to keep it as separate project. 

Feels like a lot of code that would come in and probably wouldn't get enough attention to be properly maintained as the core library evolves -- it's already challenging to keep up with the tests : /

And there is some data coming in (`tools/pipeline/data`), which doesn't feel like something that should be making the repo heavier for everyone else who wouldn't use the web app -- still, the idea is very nice because it opens the door to more users!

Suggestion: a link in the documentation pointing to your (standalone) project would to the job?

**Comment by ashwinvaidya17** [comment]
I agree with @jpcbertoldo. Since we have a small team, maintenance will be challenging for us and might detract from the core repository. It is better if this remains a separate repository. We can always link to this in the README, and you can also create a post with screenshots here https://github.com/openvinotoolkit/anomalib/discussions/categories/show-and-tell. We can also create an entry on our documentation (https://openvinotoolkit.github.io/anomalib/) to point to your project. This way, you will also retain the flexibility to update your pipeline as quickly as needed. With that said, the entire team appreciates your hardwork and it is very encouraging to see people build cool stuff using our library.

**Comment by vnk8071** [comment]
Thanks @ashwinvaidya17 @jpcbertoldo for quickly comment and give some suggestions. And I have already create discussion show and tell with title Pipeline training and inference on UI (https://github.com/openvinotoolkit/anomalib/discussions/733). Can guys see my discuss and feedback for improving complete my contribute.

I am very happiness to contribute little things useful from Anomalib library.

**Comment by ashwinvaidya17** [comment]
@vnk8071 Can I close this PR? Also, would you be willing to create a PR to add a section for **Community Projects** in the readme and point to the Discussion and your github repo? Otherwise I can create a PR for that.

**Pull request closed without merging**
