### PR TITLE
fix bug expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1,…

### LINKED ISSUE #1798: [Bug]: patchcore pytorch error
Using pathcore gives the following torch error.:

`RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)`

See the log sections for the full error.

### Dataset

Folder

### Model

PatchCore

### Steps to reproduce the behavior

I am trying to use patchcore as by tutorial. I am using a fresh install of anomalib 1.0.0.dev.
Running the following produce an error.
```

# Import the datamodule
from anomalib.data import Folder
from anomalib.data.utils import TestSplitMode
torchmetrics.functional.auc = AUROC # needed otherwise i get an import error

# Import the required modules
from anomalib.data import MVTec
from anomalib.models import Patchcore
from anomalib.engine import Engine


# Create the datamodule
datamodule = Folder(
    root='myfolder"',
    normal_dir="OK",
    abnormal_dir="KO",
    image_size=(256, 256),
    test_split_mode=TestSplitMode.SYNTHETIC,
    task="segmentation",
)

# Setup the datamodule

datamodule.setup()

model = Patchcore()

engine = Engine()

```

### OS information

OS information:
- OS: Ubuntu 22.04
- Python version: 3.10
- Anomalib version: '1.0.0dev'
- PyTorch version: '2.2.1+cu121'
- CPU

### Expected behavior

to run without errors

### Screenshots

_No response_

### Pip/GitHub

GitHub

### What version/branch did you use?

_No response_

### Configuration YAML

```yaml
?
```

### Logs

```shell
RuntimeError                              Traceback (most recent call last)
Cell In[34], line 7
      3 from anomalib.models import Patchcore
      4 from anomalib.engine import Engine
----> 7 model = Patchcore()
      9 engine = Engine()

File ~/code/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:53, in Patchcore.__init__(self, backbone, layers, pre_trained, coreset_sampling_ratio, num_neighbors)
     43 def __init__(
     44     self,
     45     backbone: str = "wide_resnet50_2",
   (...)
     49     num_neighbors: int = 9,
     50 ) -> None:
     51     super().__init__()
---> 53     self.model: PatchcoreModel = PatchcoreModel(
     54         backbone=backbone,
     55         pre_trained=pre_trained,
     56         layers=layers,
     57         num_neighbors=num_neighbors,
     58     )
     59     self.coreset_sampling_ratio = coreset_sampling_ratio
     60     self.embeddings: list[torch.Tensor] = []

File ~/code/anomalib/src/anomalib/models/image/patchcore/torch_model.py:55, in PatchcoreModel.__init__(self, layers, backbone, pre_trained, num_neighbors)
     49 self.feature_extractor = TimmFeatureExtractor(
     50     backbone=self.backbone,
     51     pre_trained=pre_trained,
     52     layers=self.layers,
     53 )
     54 self.feature_pooler = torch.nn.AvgPool2d(3, 1, 1)
---> 55 self.anomaly_map_generator = AnomalyMapGenerator()
     57 self.register_buffer("memory_bank", torch.Tensor())
     58 self.memory_bank: torch.Tensor

File ~/code/anomalib/src/anomalib/models/image/patchcore/anomaly_map.py:30, in AnomalyMapGenerator.__init__(self, sigma)
     28 super().__init__()
     29 kernel_size = 2 * int(4.0 * sigma + 0.5) + 1
---> 30 self.blur = GaussianBlur2d(kernel_size=(kernel_size, kernel_size), sigma=(sigma, sigma), channels=1)

File ~/code/anomalib/src/anomalib/models/components/filters/blur.py:68, in GaussianBlur2d.__init__(self, sigma, channels, kernel_size, normalize, border_type, padding)
     66     self.kernel = normalize_kernel2d(self.kernel)
     67 self.kernel.unsqueeze_(0).unsqueeze_(0)
---> 68 self.kernel = self.kernel.expand(self.channels, -1, -1, -1)
     69 self.border_type = border_type
     70 self.padding = padding

RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by qkhanh711**
… -1]): the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)

## 📝 Description

- Fix bug when I'm trying to run PatchCore and PaDiM 
- 🛠️ Fixes #1798 

## ✨ Changes

Select what type of change your PR is:

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x] 🔨 Refactor (non-breaking change which refactors the code base)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

Before you submit your pull request, please make sure you have completed the following steps:

- [x] 📋 I have summarized my changes in the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) and followed the guidelines for my type of change (skip for minor changes, documentation updates, and test enhancements).
- [x] 📚 I have made the necessary updates to the documentation (if applicable).
- [ ] 🧪 I have written tests that support my changes and prove that my fix is effective or my feature works (if applicable).

For more information about code review checklists, see the [Code Review Checklist](../docs/source/markdown/guides/developer/code_review_checklist.md).

### CODE REVIEW

**Comment by samet-akcay** [comment]
Hi @qkhanh711, can you provide a more descriptive title and description to the PR?

**Comment by qkhanh711** [comment]
> Hi @qkhanh711, can you provide a more descriptive title and description to the PR?

It happened  when I clone anomalib repository. After installing, I have ran the 201_fastflow.ipynb (anomalib/notebooks/200_models/)
and change the model from Fastflow to Patchcore
And I got this error:

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[7], [line 1](vscode-notebook-cell:?execution_count=7&line=1)
----> [1](vscode-notebook-cell:?execution_count=7&line=1) model = Patchcore(
      [2](vscode-notebook-cell:?execution_count=7&line=2)     coreset_sampling_ratio=0.001
      [3](vscode-notebook-cell:?execution_count=7&line=3) )

File [~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:51](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:51), in Patchcore.__init__(self, backbone, layers, pre_trained, coreset_sampling_ratio, num_neighbors)
     [41](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:41) def __init__(
     [42](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:42)     self,
     [43](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:43)     backbone: str = "wide_resnet50_2",
   (...)
     [47](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:47)     num_neighbors: int = 9,
     [48](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:48) ) -> None:
     [49](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:49)     super().__init__()
---> [51](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:51)     self.model: PatchcoreModel = PatchcoreModel(
     [52](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:52)         backbone=backbone,
     [53](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:53)         pre_trained=pre_trained,
     [54](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:54)         layers=layers,
     [55](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:55)         num_neighbors=num_neighbors,
     [56](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:56)     )
     [57](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:57)     self.coreset_sampling_ratio = coreset_sampling_ratio
     [58](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/lightning_model.py:58)     self.embeddings: list[torch.Tensor] = []

File [~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/torch_model.py:54](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/image/patchcore/torch_model.py:54), in PatchcoreModel.__init__(self, layers, backbone, pre_trained, num_neighbors)
...
---> [68](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/components/filters/blur.py:68) self.kernel = self.kernel.expand(self.channels, -1, -1, -1)
     [69](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/components/filters/blur.py:69) self.border_type = border_type
     [70](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225041494c227d.vscode-resource.vscode-cdn.net/home/khanhnq/Code/computer_vision/EvaluateAD/~/Code/computer_vision/EvaluateAD/anomalib/src/anomalib/models/components/filters/blur.py:70) self.padding = padding

RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?a5c81f2d-028b-431a-8cf6-2f39b9616f11) or open in a [text editor](command:workbench.action.openLargeOutput?a5c81f2d-028b-431a-8cf6-2f39b9616f11). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...`

**Comment by ashwinvaidya17** [comment]
@qkhanh711 are you using the latest main branch? I am not able to reproduce the issue locally.
These are my relevant changes to `201_fastflow.ipynb`

```python
datamodule = MVTec(
    root=dataset_root,
    category="bottle",
    image_size=[256, 256],
    train_batch_size=32,
    eval_batch_size=32,
    num_workers=0,
    task=task,
)

model = Patchcore(backbone="wide_resnet50_2")

engine = Engine(
    pixel_metrics="AUROC",
    accelerator="auto",  # \<"cpu", "gpu", "tpu", "ipu", "hpu", "auto">,
    devices=1,
    logger=False,
)
```

**Comment by qkhanh711** [comment]
> @qkhanh711 are you using the latest main branch? I am not able to reproduce the issue locally. These are my relevant changes to `201_fastflow.ipynb`
> 
> ```python
> datamodule = MVTec(
>     root=dataset_root,
>     category="bottle",
>     image_size=[256, 256],
>     train_batch_size=32,
>     eval_batch_size=32,
>     num_workers=0,
>     task=task,
> )
> 
> model = Patchcore(backbone="wide_resnet50_2")
> 
> engine = Engine(
>     pixel_metrics="AUROC",
>     accelerator="auto",  # \<"cpu", "gpu", "tpu", "ipu", "hpu", "auto">,
>     devices=1,
>     logger=False,
> )
> ```

yes, I'm using the main branch of https://github.com/openvinotoolkit/anomalib.git and a met this. 
anw, thank you for your answer.
Screenshot from 2024-03-25 22-35-29
ut with the original repository, I still encountered this bug

**Comment by windhorse777** [comment]
do you solve this problem? I enchanted the same bug when running the 000 geting__started

**Comment by qkhanh711** [comment]
> do you solve this problem? I enchanted the same bug when running the 000 geting__started
in line 68 of anomalib/src/anomalib/models/components/filters/blur.py
turn  self.kernel = self.kernel.expand(self.channels, -1, -1, -1) to  self.kernel = self.kernel.expand(self.channels, -1, -1, -1, -1)

**Comment by samet-akcay** [comment]
https://github.com/openvinotoolkit/anomalib/pull/1944 addressed this issue. This is no longer needed. Thanks a lot for reporting and proposing a fix.

**Comment by prasen832** [comment]
Facing same error...

from anomalib.data import MVTec
from anomalib.models import Patchcore
from anomalib.engine import Engine

C:\Users\EmageVision\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated and will be removed in a future release
  "class": algorithms.Blowfish,
  
 # Initialize the datamodule, model and engine

datamodule = MVTec()
model = Patchcore()
engine = Engine()

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[2], line 4
      1 # Initialize the datamodule, model and engine
      3 datamodule = MVTec()
----> 4 model = Patchcore()
      5 engine = Engine()

File ~\anaconda3\Lib\site-packages\anomalib\models\image\patchcore\lightning_model.py:51, in Patchcore.__init__(self, backbone, layers, pre_trained, coreset_sampling_ratio, num_neighbors)
     41 def __init__(
     42     self,
     43     backbone: str = "wide_resnet50_2",
   (...)
     47     num_neighbors: int = 9,
     48 ) -> None:
     49     super().__init__()
---> 51     self.model: PatchcoreModel = PatchcoreModel(
     52         backbone=backbone,
     53         pre_trained=pre_trained,
     54         layers=layers,
     55         num_neighbors=num_neighbors,
     56     )
     57     self.coreset_sampling_ratio = coreset_sampling_ratio
     58     self.embeddings: list[torch.Tensor] = []

File ~\anaconda3\Lib\site-packages\anomalib\models\image\patchcore\torch_model.py:54, in PatchcoreModel.__init__(self, layers, backbone, pre_trained, num_neighbors)
     48 self.feature_extractor = TimmFeatureExtractor(
     49     backbone=self.backbone,
     50     pre_trained=pre_trained,
     51     layers=self.layers,
     52 )
     53 self.feature_pooler = torch.nn.AvgPool2d(3, 1, 1)
---> 54 self.anomaly_map_generator = AnomalyMapGenerator()
     56 self.register_buffer("memory_bank", torch.Tensor())
     57 self.memory_bank: torch.Tensor

File ~\anaconda3\Lib\site-packages\anomalib\models\image\patchcore\anomaly_map.py:29, in AnomalyMapGenerator.__init__(self, sigma)
     27 super().__init__()
     28 kernel_size = 2 * int(4.0 * sigma + 0.5) + 1
---> 29 self.blur = GaussianBlur2d(kernel_size=(kernel_size, kernel_size), sigma=(sigma, sigma), channels=1)

File ~\anaconda3\Lib\site-packages\anomalib\models\components\filters\blur.py:68, in GaussianBlur2d.__init__(self, sigma, channels, kernel_size, normalize, border_type, padding)
     66     self.kernel = normalize_kernel2d(self.kernel)
     67 self.kernel.unsqueeze_(0).unsqueeze_(0)
---> 68 self.kernel = self.kernel.expand(self.channels, -1, -1, -1)
     69 self.border_type = border_type
     70 self.padding = padding

RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)

**Pull request closed without merging**
