### PR TITLE
Separate train and validation transformations

### PR DESCRIPTION
**Pull request by alexriedel1**
This introduces separate training and validation transformation to be defined in the respective model configs. 

If nothing is defined, it will fall back to default behaviour at any time.
If only training transformations are defined, validation transformations will be set equal to those. 

An alternative for handling this is raising a user warning, that one kind of transformations is defined and the other is not?

If there's something missing or if this should be implemented completely different, let me know.

### CODE REVIEW

**Comment by samet-akcay** [comment]
@alexriedel1 the CI has failed due to formatting. We bumped up the black version due to some dependency conflicts, causing some formatting changes. Would you be able to update your black version, and run the formatting again. 
For more details, see here:

https://github.com/openvinotoolkit/anomalib/blob/development/tox.ini#L16
https://github.com/openvinotoolkit/anomalib/blob/development/.pre-commit-config.yaml#L15

**Comment by alexriedel1** [comment]
> @alexriedel1 the CI has failed due to formatting. We bumped up the black version due to some dependency conflicts, causing some formatting changes. Would you be able to update your black version, and run the formatting again. For more details, see here:
> 
> https://github.com/openvinotoolkit/anomalib/blob/development/tox.ini#L16 https://github.com/openvinotoolkit/anomalib/blob/development/.pre-commit-config.yaml#L15

should be fine now.

```
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Passed
Check for added large files..............................................Passed
Debug Statements (Python)................................................Passed
Detect Private Key.......................................................Passed
black....................................................................Passed
isort....................................................................Passed
prettier.................................................................Passed
flake8...................................................................Passed
pylint...................................................................Passed
mypy.....................................................................Passed
pydocstyle...............................................................Passed
```

**Review by djdameln — APPROVED** [review]
Thanks, this is a nice enhancement

**Review by samet-akcay — APPROVED** [review]
Thanks @alexriedel1!

Our CI is broken now. We'll merge this PR once we fix the CI and run the PR one more time.

**Comment by alexriedel1** [comment]
I just merged the development branch

**Pull request merged**
