### PR TITLE
Remove torchvision and torchtext

### PR DESCRIPTION
**Pull request by samet-akcay**
# Description

- Remove `torchvision` and `torchtext` from the base requirements.

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] I have added a summary of my changes to the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) (not for minor changes, docs and tests).

### CODE REVIEW

**Review by djdameln — COMMENTED** [review]
Is this safe? How do we know the correct version is installed?

**Review by ashwinvaidya17 — COMMENTED** [review]
Is torchtext automatically installed? If I remember correctly, SC docker files contain additional torchtext dependency in the base image. But that maybe just for fixing the version.

**Comment by samet-akcay** [comment]
> nstalled? If I remember correctly, SC docker files contain additi

We don't have a check for torch, but do have for these. Actually this would be even more problematic

**Comment by ashwinvaidya17** [comment]
> > nstalled? If I remember correctly, SC docker files contain additi
> 
> We don't have a check for torch, but do have for these. Actually this would be even more problematic

Alright. Let's roll with this then

**Review by ashwinvaidya17 — APPROVED** [review]

**Comment by samet-akcay** [comment]
@ashwinvaidya17, I also feel that we should also have `anomalib install` option that comes with the CLI. I think that would be the safest bet

**Review by djdameln — APPROVED** [review]

**Pull request merged**
