### PR TITLE
Fix normalization

### PR DESCRIPTION
**Pull request by alexriedel1**
## 📝 Description

Fixes: https://github.com/openvinotoolkit/anomalib/discussions/2122#discussioncomment-9740488 and https://github.com/openvinotoolkit/anomalib/issues/2027 and https://github.com/openvinotoolkit/anomalib/issues/2139#issue-2352819822

The normalization metrics are resetted before every validation. Is there any flaw in this logic or does it makes sense, so that models that have very different anomaly map and pred score magnitudes during training epochs are optimally normalized.

## ✨ Changes

Select what type of change your PR is:

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔨 Refactor (non-breaking change which refactors the code base)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 Documentation update
- [ ] 🔒 Security update

## ✅ Checklist

Before you submit your pull request, please make sure you have completed the following steps:

- [ ] 📋 I have summarized my changes in the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) and followed the guidelines for my type of change (skip for minor changes, documentation updates, and test enhancements).
- [ ] 📚 I have made the necessary updates to the documentation (if applicable).
- [ ] 🧪 I have written tests that support my changes and prove that my fix is effective or my feature works (if applicable).

For more information about code review checklists, see the [Code Review Checklist](https://github.com/openvinotoolkit/anomalib/blob/main/docs/source/markdown/guides/developer/code_review_checklist.md).

### CODE REVIEW

**Comment by alexriedel1** [comment]
Ah I missed some things when saving the model. However I can already tell you it works much better if you rely on pred_scores for downstream tasks!

**Review by samet-akcay — CHANGES_REQUESTED** [review]
Thanks @alexriedel1! I only have super minor comments

**Review by samet-akcay — APPROVED** [review]

**Comment by alsmeirelles** [comment]
Hello guys,

With this commit, people that used to load a state dict with a model trained prior to this and has only the "normalization_metric" in state dict get the error bellow (in this case, using EfficientAd):

**Comment by alexriedel1** [comment]
> Hello guys,
> 
> With this commit, people that used to load a state dict with a model trained prior to this and has only the "normalization_metric" in state dict get the error bellow (in this case, using EfficientAd):
> 
> AttributeError: 'EfficientAd' object has no attribute 'anomaly_maps_normalization_metrics'
> 
> This is due to the fact that there was no difference in metrics normalization before and with the new fix, the attribute is not defined:
> 
> (AnomalyModule -> load_state_dict: line 171) if "anomaly_maps_normalization_class" in state_dict: self.anomaly_maps_normalization_metrics = self._get_instance(state_dict, "anomaly_maps_normalization_class")
> 
> So, my question is: what should I do to fix this without retraining the model?

The easiest would be to install the anomalib version you were using at the time of model training.

**Pull request merged**
