### PR TITLE
Add URL verification for downloading dataset

### PR DESCRIPTION
**Pull request by yunchu**
## 📝 Description

This PR is for fixing the medium severity issue reported by bandit scanning.
```
>> Issue: [B310:blacklist] Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.
   Severity: Medium   Confidence: High
   CWE: CWE-22 (https://cwe.mitre.org/data/definitions/22.html)
   More Info: https://bandit.readthedocs.io/en/1.7.6/blacklists/blacklist_calls.html#b310-urllib-urlopen
   Location: /home/runner/work/anomalib/anomalib/src/anomalib/data/utils/download.py:298:12
297	        with DownloadProgressBar(unit="B", unit_scale=True, miniters=1, desc=info.name) as progress_bar:
298	            urlretrieve(  # noqa: S310
299	                url=f"{info.url}",
300	                filename=downloaded_file_path,
301	                reporthook=progress_bar.update_to,
302	            )
303	        logger.info("Checking the hash of the downloaded file.")
```

in addition to this change, specify the node version number to the pre-commit config to help contributors to run the pre-commit on their local environment without having manual installation of the node component.

🛠️ Fixes # (issue number)

## ✨ Changes

Select what type of change your PR is:

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔨 Refactor (non-breaking change which refactors the code base)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 Documentation update

## ✅ Checklist

Before you submit your pull request, please make sure you have completed the following steps:

- [ ] 📋 I have summarized my changes in the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) and followed the guidelines for my type of change (skip for minor changes, documentation updates, and test enhancements).
- [ ] 📚 I have made the necessary updates to the documentation (if applicable).
- [ ] 🧪 I have written tests that support my changes and prove that my fix is effective or my feature works (if applicable).

### CODE REVIEW

**Comment by samet-akcay** [comment]
We recently merged #1598 which potentially cause this fail. I'm surprised that the CI did not fail in that PR but here :/

**Comment by samet-akcay** [comment]
@yunchu, I'm aware that it is not the scope of your changes, but would you be able to update these imports to pass the CI. Sorry for the inconvenience :(

```bash
FAILED notebooks/000_getting_started/001_getting_started.ipynb:: - ModuleNotFoundError: No module named 'anomalib.utils.types'
FAILED notebooks/100_datamodules/101_btech.ipynb:: - ModuleNotFoundError: No module named 'anomalib.utils.types'
FAILED notebooks/100_datamodules/103_folder.ipynb:: - ModuleNotFoundError: No module named 'anomalib.utils.types'
FAILED notebooks/200_models/201_fastflow.ipynb:: - ModuleNotFoundError: No module named 'anomalib.utils.types'
```

You will need to change `from anomalib.utils.types import TaskType` to

```python
from anomalib import TaskType
```

**Comment by yunchu** [comment]
> @yunchu, I'm aware that it is not the scope of your changes, but would you be able to update these imports to pass the CI. Sorry for the inconvenience :(
> 
> ```shell
> FAILED notebooks/000_getting_started/001_getting_started.ipynb:: - ModuleNotFoundError: No module named 'anomalib.utils.types'
> FAILED notebooks/100_datamodules/101_btech.ipynb:: - ModuleNotFoundError: No module named 'anomalib.utils.types'
> FAILED notebooks/100_datamodules/103_folder.ipynb:: - ModuleNotFoundError: No module named 'anomalib.utils.types'
> FAILED notebooks/200_models/201_fastflow.ipynb:: - ModuleNotFoundError: No module named 'anomalib.utils.types'
> ```
> 
> You might need to change `from anomalib.utils.types import TaskType` to
> 
> ```python
> from anomalib import TaskType
> ```

no problems. thanks for your help!

**Review by samet-akcay — APPROVED** [review]
lgtm thanks!

**Pull request merged**
