### PR TITLE
Efficient ad reduced memory footprint

### LINKED ISSUE #1301: [Task]: EfficientAD OutOfMemory exception (fix included)
### What is the motivation for this task?

I ran into an OutOfMemory exception when calculating the teacher channel mean and standard deviation while training the EfficientAD model.

### Describe the solution you'd like

I fixed this by not saving the teacher outputs to a list but instead iterating the dataloader twice.
This increases the runtime of the teacher_channel_mean_std() function, but only if the teacher outputs don't fit into memory.

I could create a pull request from [my branch](https://github.com/MG109/anomalib/blob/efficient_ad_reduced_memory_footprint/src/anomalib/models/efficient_ad/lightning_model.py), but I didn't manage to get the pre-commit hooks running.

```python
    @torch.no_grad()
    def teacher_channel_mean_std(self, dataloader: DataLoader) -> dict[str, Tensor]:
        """Calculate the mean and std of the teacher models activations.

        Args:
            dataloader (DataLoader): Dataloader of the respective dataset.

        Returns:
            dict[str, Tensor]: Dictionary of channel-wise mean and std
        """
        y_means = []
        teacher_outputs = []
        means_distance = []

        logger.info("Calculate teacher channel mean and std")
        try:
            for batch in tqdm.tqdm(dataloader, desc="Calculate teacher channel mean", position=0, leave=True):
                y = self.model.teacher(batch["image"].to(self.device))
                y_means.append(torch.mean(y, dim=[0, 2, 3]))
                teacher_outputs.append(y)
        except RuntimeError as e:
            teacher_outputs = []
            y_means = []
            torch.cuda.empty_cache()
            logger.info("Recovering from OutOfMemory Exception by using workaround with longer runtime")
            for batch in tqdm.tqdm(dataloader, desc="Calculate teacher channel mean", position=0, leave=True):
                y = self.model.teacher(batch["image"].to(self.device))
                y_means.append(torch.mean(y, dim=[0, 2, 3]))

        channel_mean = torch.mean(torch.stack(y_means), dim=0)[None, :, None, None]

        if len(teacher_outputs) > 0:
            for y in tqdm.tqdm(teacher_outputs, desc="Calculate teacher channel std", position=0, leave=True):
                distance = (y - channel_mean) ** 2
                means_distance.append(torch.mean(distance, dim=[0, 2, 3]))
        else:
            for batch in tqdm.tqdm(dataloader, desc="Calculate teacher channel std", position=0, leave=True):
                y = self.model.teacher(batch["image"].to(self.device))
                distance = (y - channel_mean) ** 2
                means_distance.append(torch.mean(distance, dim=[0, 2, 3]))

        channel_var = torch.mean(torch.stack(means_distance), dim=0)[None, :, None, None]
        channel_std = torch.sqrt(channel_var)
        return {"mean": channel_mean, "std": channel_std}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MG109**
## Description

I ran into an OutOfMemory exception when calculating the teacher channel mean and standard deviation while training the EfficientAD model. I fixed this by not saving the teacher outputs to a list but instead iterating the dataloader twice.

- Fixes #1301 

- **TODO**: Sort out pre-commit stuff (couldn't get the pre-commit hooks running)

- Maybe: Implement 'online' mean and variance calculation, see https://github.com/openvinotoolkit/anomalib/issues/1301#issuecomment-1693126642

## Changes

<details>
<summary>Describe the changes you made</summary>

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

</details>

## Checklist

<details>
<summary>Ensure that you followed the following</summary>

- [ ] I have added a summary of my changes to the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) (not for minor changes, docs and tests).
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas (If applicable)
- [ ] I have made corresponding changes to the documentation (If applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (If applicable)

</details>

### CODE REVIEW

**Comment by samet-akcay** [comment]
@alexriedel1, would you like to review this PR?

**Comment by alexriedel1** [comment]
> @alexriedel1, would you like to review this PR?

Sure! I would prefer to only use one method without going for the try except. So just implement the twice iterating method as Standard @MG109.

In my view the memory is not solved by this, because it only reduces memory consumption by a half. For really large datasets it will still fail.

There are two ways to overcome this:
1 only use as many samples as memory is available for mean and std calculation.
2 use an online mean and sts calculation method that doesnt need to store all single values.

**Comment by alexriedel1** [comment]
looks good to me!

**Review by samet-akcay — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
