### PR TITLE
Ml flow support #1759

### LINKED ISSUE #1759: ✨ MLFlow support
### Discussed in https://github.com/openvinotoolkit/anomalib/discussions/1206

<div type='discussions-op-text'>

<sup>Originally posted by **Ravio1i** July 12, 2023</sup>
### What is the motivation for this task?

We are using MlFlow. Is it planned to support sending logs to mlflow?

### Describe the solution you'd like

```yaml
  logger: mlflow
```

### Additional context

_No response_</div>

### PR DESCRIPTION
**Pull request by Bepitic**
## 📝 Description

- Provide a clear summary of the changes and the issue that has been addressed.
- 🛠️ Fixes #1759 

## ✨ Changes

Select what type of change your PR is:

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔨 Refactor (non-breaking change which refactors the code base)
- [X] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 Documentation update
- [ ] 🔒 Security update

## ✅ Checklist

Before you submit your pull request, please make sure you have completed the following steps:

- [ ] 📋 I have summarized my changes in the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) and followed the guidelines for my type of change (skip for minor changes, documentation updates, and test enhancements).
- [X] 📚 I have made the necessary updates to the documentation (if applicable).
- [ ] 🧪 I have written tests that support my changes and prove that my fix is effective or my feature works (if applicable).

For more information about code review checklists, see the [Code Review Checklist](../docs/source/markdown/guides/developer/code_review_checklist.md).

### CODE REVIEW

**Comment by Bepitic** [comment]
Hello, I just saw another PR for the same Issue.

I wish to enter GSoC for the following projects:

 14. Add time-series anomaly detection support to Anomalib.
 15. AnomalyGPT: Integrating Vision Language Models (VLMs) in Anomalib for zero- and few-shot anomaly detection.

Could you refer me to more complicated issues/bugs/tasks closely related to this project? (or assign me  :) )

**Comment by samet-akcay** [comment]
@Bepitic, would it be ok if we close this PR since it is a duplicate of https://github.com/openvinotoolkit/anomalib/pull/1847? Thanks a lot for your contribution, and apologies for the inconvenience :/

**Comment by Bepitic** [comment]
Yes, no worries, @samet-akcay.
I just want to help.

**Comment by samet-akcay** [comment]
Thanks, much appreciated. Let us know if you are interested in any of the [issues](https://github.com/openvinotoolkit/anomalib/issues)

**Pull request closed without merging**
