### PR TITLE
[CI] Update coverage tool to codecov for pre-merge

### PR DESCRIPTION
**Pull request by yunchu**
# Description

- Replaced coverage reporting tool from Codacy to Codecov for the pre-merge job in the workflow

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://github.com/openvinotoolkit/anomalib/blob/main/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] I have added a summary of my changes to the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) (not for minor changes, docs and tests).

### CODE REVIEW

**Comment by samet-akcay** [comment]
@yunchu, thanks for your PR. Is it possible to do this without setting it up from https://app.codecov.io/gh/openvinotoolkit?

**Comment by yunchu** [comment]
> @yunchu, thanks for your PR. Is it possible to do this without setting it up from https://app.codecov.io/gh/openvinotoolkit?

@samet-akcay AFAIK, for the public repo, it doesn't need to register it and corresponding token is also not required.

**Comment by samet-akcay** [comment]
> > @yunchu, thanks for your PR. Is it possible to do this without setting it up from https://app.codecov.io/gh/openvinotoolkit?
> 
> @samet-akcay AFAIK, for the public repo, it doesn't need to register it and corresponding token is also not required.

hm, if this is the case, it's good news!

**Comment by samet-akcay** [comment]
Any idea about how to use codecov badge on the readme file? For codacy, there is this line on the readme 
[Codacy Badge](https://www.codacy.com/gh/openvinotoolkit/anomalib/dashboard?utm_source=github.com&utm_medium=referral&utm_content=openvinotoolkit/anomalib&utm_campaign=Badge_Coverage)

To get this, I assume we need to somehow connect to codecov's anomalib dashboard?

**Comment by yunchu** [comment]
um... it looks like to have signing up to the codecov.io
here is a guild for the badge and need to get into the "setting" menu but cannot see it without sign up to there.
https://docs.codecov.com/docs/status-badges

**Comment by samet-akcay** [comment]
Yeah, I think we need to add both anomalib and training extensions to codecov to get this. I can only see `datumaro` and `mmdetection` repos in codecov. 

image

**Comment by yunchu** [comment]
how about just putting [codecov](https://codecov.io/gh/openvinotoolkit/anomalib) to the README.md?

**Comment by yunchu** [comment]
I guess the number of the coverage for the default branch should be reported to the codecov to show it correctly.

**Review by ashwinvaidya17 — APPROVED** [review]
Thanks for adding this

**Review by samet-akcay — APPROVED** [review]
Thanks!

**Pull request merged**
