### PR TITLE
Dockerfile enhancements

### PR DESCRIPTION
**Pull request by LukasBommes**
# Description

Improves the Dockerfile. This fixes issue #171.

I removed the caching of the MVTec dataset, since it is anyway downloaded upon calling `tools/train.py`. Furthermore, anomalib is installed inside the image.

## Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://openvinotoolkit.github.io/anomalib/guides/using_pre_commit.html#pre-commit-hooks) of this project.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

### CODE REVIEW

**Comment by LukasBommes** [comment]
Maybe, we could also add a brief usage description in the readme. It could state that the image is built as follows:
`docker build . --tag=anomalib`
and can be run from the project's root directory with
`docker run -it --ipc=host --env="DISPLAY" --gpus=all -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v "$(pwd)":/anomalib anomalib /bin/bash`
It may also require disabling access control to the X11 server by running `xhost +` on the host. This is needed to forward graphical output of the container to the host.

**Comment by samet-akcay** [comment]
> Maybe, we could also add a brief usage description in the readme. It could state that the image is built as follows:
docker build . --tag=anomalib
and can be run from the project's root directory with
docker run -it --ipc=host --env="DISPLAY" --gpus=all -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v "$(pwd)":/anomalib anomalib /bin/bash
It may also require disabling access control to the X11 server by running xhost + on the host. This is needed to forward graphical output of the container to the host.

@LukasBommes, we have a [section](https://github.com/openvinotoolkit/anomalib/blob/development/docs/source/guides/developing_on_docker.rst) in the documentation explaining how to develop on docker. Would it be an idea to include these descriptions as well as linking the dataset as you mentioned in the issue? What do you think?

**Comment by LukasBommes** [comment]
The "Developing on Docker" section seems a good place. I will add the usage comment there.

The dataset is downloaded when running `tools/train.py` for the first time, right? Hence, I would just leave it to the python script to perform the download. When the container is run with the `-v "$(pwd)":/anomalib` argument will map all directory contents (including the dowanloaded dataset) into the container. Does that sound like a good solution? Otherwise, there would be redundant code for the download (once in the python code and once in the Docker entrypoint script).

**Comment by LukasBommes** [comment]
Actually, the "Developing on Docker" section could be cleaned up a bit. I n my opinion it is unecessary to describe the use of the VSCode Remote-Containers extension. I'd just put the bare minimum of shell commands for building and running the container there. If someone wants to use the VSCode extension, then he could refer to the respective doumentation in VSCode.
What do you think?

**Comment by ashwinvaidya17** [comment]
closes #171

**Review by ashwinvaidya17 — APPROVED** [review]
Thanks for looking into this! The original image was created for the gitlab runner but it has been deprecated. It is a good idea to decouple bare minimum development environment and the rest of the code and dataset. Mapping directory makes sense at this point. Also, I like the idea of forwarding X11 to host machine. Can you add it to the documentation/create a ticket for it?

**Pull request merged**
