### PR TITLE
Fixed outdated info in readme

### PR DESCRIPTION
**Pull request by blaz-r**
# Description

I fixed links in the readme that were not working. 
* Most of them were broken due to move of `anomalib` into `src` directory.
* There was also a link to hardware section of the documentation that no longer exists so I changed that as well.
* Since some of the links were relative and some used entire url, I also unified them all to be relative if referring to the file from the repository.

### CODE REVIEW

**Comment by blaz-r** [comment]
Also fixed commands:
* added `src` before anomalib in path
* `run` in weight path
* --meta_data changed to --metadata

**Review by samet-akcay — APPROVED** [review]
Thanks for the fix @blaz-r

**Comment by blaz-r** [comment]
@samet-akcay one thing I noticed is that meta_data was changed to metadata, so I fixed that as I said before. But in version 4.0.0 there still is meta_data used. 
Is my change correct to reflect the current state on main branch or should it be as it is v4.0.0?

**Comment by samet-akcay** [comment]
it's correct. Those changes will be in effect in v0.5.0

**Pull request merged**
