### PR TITLE
optimize compute_anomaly_score by using torch native funcrtions

### PR DESCRIPTION
**Pull request by alexriedel1**
Hey,
I realized that the `compute_anomy_score` method https://github.com/openvinotoolkit/anomalib/blob/ee8807b48d7c5ccfe9f5ff976fb6d6dac0247f0a/anomalib/models/patchcore/model.py#L69 can be optimized by using torch native functions that might vectorize better.

Using a GPU, the execution time reduces from `0.17330350000000116s` to `0.00022549999999910142s` (~700x faster)

### CODE REVIEW

**Review by samet-akcay — APPROVED** [review]
Thanks @alexriedel1! That's a good catch! We'd be able to merge it after @djdameln approves the PR

**Comment by alexriedel1** [comment]
> Thanks @alexriedel1! That's a good catch! We'd be able to merge it after @djdameln approves the PR

Theres one more thing I'd like to adress: `torch.cdist()` is slow (https://github.com/pytorch/pytorch/issues/15253)
https://github.com/openvinotoolkit/anomalib/blob/5a5e552cb4f3dbcdc8d9bff788b9cbcd445f9496/anomalib/models/patchcore/model.py#L239

This cdist implementation is fast: https://github.com/pytorch/pytorch/issues/15253#issuecomment-491467128

Maybe you can think about using the version mentioned above. I can create another pull request for this.

**Review by djdameln — APPROVED** [review]
Thanks for addressing this @alexriedel1!

**Comment by samet-akcay** [comment]
@alexriedel1, would you like to address that in a separate PR, or in this one? If the former, I could merge this one.

**Comment by alexriedel1** [comment]
> @alexriedel1, would you like to address that in a separate PR, or in this one? If the former, I could merge this one.

Let me do another PR so you can merge this one

**Pull request merged**
