### PR TITLE
reutrn results of load_state_dict func

### PR DESCRIPTION
**Pull request by zywvvd**
you have to reutrn the results of load_state_dict if you wrappered the original one

# Description

- Provide a summary of the modification as well as the issue that has been resolved. List any dependencies that this modification necessitates.

- Fixes # (issue)

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the [pre-commit style and check guidelines](https://openvinotoolkit.github.io/anomalib/guides/using_pre_commit.html#pre-commit-hooks) of this project.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

### CODE REVIEW

**Review by ashwinvaidya17 — APPROVED** [review]
Thanks for identifying this!

**Review by djdameln — APPROVED** [review]
Thanks for spotting this! 

@ashwinvaidya17 do you think this may have introduced any bugs on the OTE side?

**Comment by ashwinvaidya17** [comment]
> Thanks for spotting this!
> 
> @ashwinvaidya17 do you think this may have introduced any bugs on the OTE side?

I don't think so as we load the model outside pytorch lightning trainer. Load state dict returns a tuple with missing keys and unexpected keys. We don't use these value anywhere. It is possible that the lightning trainer may be using it internally for checkpoints but I haven't seen any issues on OTE for now.

**Comment by samet-akcay** [comment]
Thanks @zywvvd, and welcome to the anomalib contributor community!

**Pull request merged**
