### PR TITLE
🔨 Pass `pre-trained` from config to `ModelLightning`

### PR DESCRIPTION
**Pull request by samet-akcay**
# Description

- Following #514, this PR adds `pre_trained` parameter to `ModelLightning` implementation.

## Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which refactors the code base)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the [pre-commit style and check guidelines](https://openvinotoolkit.github.io/anomalib/guides/using_pre_commit.html#pre-commit-hooks) of this project.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

### CODE REVIEW

**Review by djdameln — COMMENTED** [review]
I'm having some doubts about adding this parameter. For feature extraction based models such as padim and dfm, what would be the use case of having a non pre-trained backbone? Since the training does not involve finetuning the backbone weights, the normality model would be built upon random layer activations.

**Comment by samet-akcay** [comment]
> I'm having some doubts about adding this parameter. For feature extraction based models such as padim and dfm, what would be the use case of having a non pre-trained backbone? Since the training does not involve finetuning the backbone weights, the normality model would be built upon random layer activations.

I don't know if there is a specific use-case for this. config.yaml file contains pre_trained flag. If we dont want this, maybe we could remove this from the config file itself.

Perhaps you could ask this question in PR 514 to confirm whether this actually has any use-case?

**Review by djdameln — APPROVED** [review]
Based on the discussion in the other PR (https://github.com/openvinotoolkit/anomalib/pull/514) I think this is a viable use case, so I'm happy to merge this one.

**Review by ashwinvaidya17 — APPROVED** [review]
Thanks!

**Pull request merged**
