### PR TITLE
PaDim occasionally NaNs in anomaly map

### PR DESCRIPTION
**Pull request by VdLMV**
# With custom dataset and backbone distances sometimes contains small negative numbers, possible due to imperfect pseudo inverse calculation. Solution was to clip distances to zero before sqrt.

- Solution is to clip distances to zero before sqrt.

- Fixes # (issue)

## Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the [pre-commit style and check guidelines](https://openvinotoolkit.github .io/anomalib/guides/using_pre_commit.html#pre-commit-hooks) of this project.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

### CODE REVIEW

**Comment by VdLMV** [comment]
@samet-akcay : I don't understand pre-merge fail. Plz your help.

**Comment by samet-akcay** [comment]
@VdLMV, looks like some of the tests in `tests/pre_merge/deploy/test_inferencer.py` fails with this change. I'll check it out and let you know.

**Comment by samet-akcay** [comment]
@VdLMV, your change is fine, I'll approve it. However, PADIM started to fail in the tests for some reason. It fails when the model is exported to ONNX. We'll investigate this a bit deeper.

**Comment by samet-akcay** [comment]
@VdLMV, the reason turned out to be the latest torchvision version, which causes some issues on the ONNX / OpenVINO side. I'll merge this one now.

**Pull request merged**
