### PR TITLE
Upgrade to new torch metrics

### PR DESCRIPTION
**Pull request by ashwinvaidya17**
# Description

- Change F1 to F1Score
- Fixes F1 score issue with torchmetrics>=0.6.1

## Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the [pre-commit style and check guidelines](https://openvinotoolkit.github.io/anomalib/guides/using_pre_commit.html#pre-commit-hooks) of this project.
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

### CODE REVIEW

**Review by samet-akcay — APPROVED** [review]

**Comment by djdameln** [comment]
This will cause conflicts with https://github.com/openvinotoolkit/anomalib/pull/230. Maybe it would be better to change F1 -> F1Score in that PR

**Comment by ashwinvaidya17** [comment]
> This will cause conflicts with #230. Maybe it would be better to change F1 -> F1Score in that PR

In that case should I close this or rebase and target to #230 ?

**Comment by ashwinvaidya17** [comment]
> This will cause conflicts with #230. Maybe it would be better to change F1 -> F1Score in that PR

In that case should I close this or rebase and target to #230 ?

**Comment by djdameln** [comment]
> In that case should I close this or rebase and target to #230 ?

Actually most of the lines that are changed in this PR are removed in my PR, because we no longer hard code the F1 metric. You could close this one and I'll take care of it in https://github.com/openvinotoolkit/anomalib/pull/230.

**Pull request closed without merging**
