### PR TITLE
Refactored-assert-statements-with-explicit-error-handling

### LINKED ISSUE #1654: 🔨 Refactor assert statements with explicit error handling
### What is the motivation for this task?

bandit scans treat `assert` as a potential security issue with the following warning:

```bash
>> Issue: Use of assert detected. The enclosed code will be removed when
   compiling to optimised byte code.
   Severity: Low   Confidence: High
   CWE: CWE-703 (https://cwe.mitre.org/data/definitions/703.html)
   Location: ./examples/assert.py:1
1 assert logged_in
2 display_assets()
```

### Describe the solution you'd like

remove asserts from the main codebase, only use it in the test suite.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sahusiddharth**
## 📝 Description

- Instead of using assert statements, which can be disabled in production and do not provide informative error messages, this PR replaces them with proper error handling mechanisms such as try-except blocks or raising custom exceptions.
- 🛠️ Fixes #1654
## ✨ Changes

Select what type of change your PR is:

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🔨 Refactor (non-breaking change which refactors the code base)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 Documentation update
- [ ] 🔒 Security update

## ✅ Checklist

Before you submit your pull request, please make sure you have completed the following steps:

- [ ] 📋 I have summarized my changes in the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) and followed the guidelines for my type of change (skip for minor changes, documentation updates, and test enhancements).
- [ ] 📚 I have made the necessary updates to the documentation (if applicable).
- [ ] 🧪 I have written tests that support my changes and prove that my fix is effective or my feature works (if applicable).

For more information about code review checklists, see the [Code Review Checklist](../docs/source/markdown/guides/developer/code_review_checklist.md).

### CODE REVIEW

**Comment by sahusiddharth** [comment]
@samet-akcay @ashwinvaidya17, Pre-Merge Checks / Code-Quality-Checks (pull_request) test is failing because of 

Screenshot 2024-03-07 at 4 14 01 AM

**Comment by samet-akcay** [comment]
You could ignore it by doing the following.

```python
def make_folder3d_dataset(  # noqa: C901
```

I'll create another issue to fix it. It might not be the scope of your PR

**Comment by sahusiddharth** [comment]
@samet-akcay, I have not changed the logic, I don't understand why so many test cases are failing

**Comment by sahusiddharth** [comment]
@samet-akcay and @ashwinvaidya17, there are 12 test cases that are failing now and I am finding it difficult to trace them back, can you please help me?

**Comment by ashwinvaidya17** [comment]
I've restarted the tests

**Comment by sahusiddharth** [comment]
@ashwinvaidya17, tell me what else needs to done!!

**Comment by samet-akcay** [comment]
> @ashwinvaidya17, tell me what else needs to done!!

@sahusiddharth you don't need to do anything else, the tests are passing now. We will review the PR and let you know. Thanks for your contribution!

**Review by samet-akcay — APPROVED** [review]
lgtm, thanks for your effort

**Pull request merged**
